// Programmatic SEO data for /sell-online/[slug] landing pages.
// Two page types share one route: city pages ("sell online in jaipur") and
// category pages ("sell sarees online"). Every entry carries unique local copy —
// thin doorway pages get penalized, so keep `flavor` specific and true.

export interface CityPage {
  type: 'city'
  slug: string
  name: string
  state: string
  /** One or two specific sentences about local trade — unique per page. */
  flavor: string
  /** Three example seller types used in benefit cards. */
  examples: [string, string, string]
}

export interface CategoryPage {
  type: 'category'
  slug: string
  /** Display name, e.g. "Sarees" */
  name: string
  /** Store noun, e.g. "saree store" */
  noun: string
  flavor: string
  examples: [string, string, string]
}

export const CITY_PAGES: CityPage[] = [
  { type: 'city', slug: 'delhi', name: 'Delhi', state: 'Delhi', flavor: 'From Chandni Chowk wholesalers to Karol Bagh fashion retailers, Delhi sellers already move enormous volume offline. An online store turns walk-in bargaining into round-the-clock orders from across India.', examples: ['Wholesale fashion traders', 'Electronics & accessories shops', 'Street-food and spice brands'] },
  { type: 'city', slug: 'mumbai', name: 'Mumbai', state: 'Maharashtra', flavor: 'Mumbai is the home of Indian D2C — from Crawford Market traders to home-grown fashion labels in Bandra. Buyers here expect UPI, fast checkout and Instagram-ready storefronts.', examples: ['Home-grown fashion labels', 'Jewellery & accessories designers', 'Gourmet food startups'] },
  { type: 'city', slug: 'bangalore', name: 'Bangalore', state: 'Karnataka', flavor: "Bangalore's buyers are India's most online-savvy. Boutiques in Jayanagar, organic brands in Indiranagar and artisan bakers across the city sell out through Instagram — a proper store turns that attention into trackable orders.", examples: ['Independent boutiques', 'Organic & artisanal food brands', 'Plant & home-garden studios'] },
  { type: 'city', slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana', flavor: 'Laad Bazaar bangles, Hyderabadi pearls and spice blends famous far beyond the city — Hyderabad products have buyers all over India. An online store lets you ship beyond the old city lanes.', examples: ['Pearl & bangle sellers', 'Biryani masala & pickle brands', 'Ethnic fashion boutiques'] },
  { type: 'city', slug: 'chennai', name: 'Chennai', state: 'Tamil Nadu', flavor: 'From Kanchipuram silk to temple jewellery, Chennai sellers carry products with national demand. T. Nagar gets crowded — your online store never does.', examples: ['Silk saree retailers', 'Temple jewellery makers', 'South Indian snacks brands'] },
  { type: 'city', slug: 'kolkata', name: 'Kolkata', state: 'West Bengal', flavor: 'Tant and Baluchari sarees, College Street books, mishti that people order across the country — Kolkata businesses have loyal buyers far beyond Bengal. Put a storefront on that loyalty.', examples: ['Tant & handloom saree sellers', 'Sweet shops & bakers', 'Book and stationery sellers'] },
  { type: 'city', slug: 'pune', name: 'Pune', state: 'Maharashtra', flavor: "Pune's student crowd and young professionals buy online first. Local boutiques, snack brands and handicraft sellers grow fastest when a WhatsApp share leads to a real checkout, not just a DM.", examples: ['College-area fashion boutiques', 'Bakery & chocolate makers', 'Handicraft and decor sellers'] },
  { type: 'city', slug: 'ahmedabad', name: 'Ahmedabad', state: 'Gujarat', flavor: 'Bandhani, block prints and the trading instinct of Manek Chowk — Ahmedabad sellers know commerce. An online store adds prepaid UPI orders and COD reach across India to that instinct.', examples: ['Bandhani & textile traders', 'Imitation jewellery sellers', 'Snack & farsan brands'] },
  { type: 'city', slug: 'jaipur', name: 'Jaipur', state: 'Rajasthan', flavor: 'Block-print bedsheets, blue pottery, gemstones and juttis — Jaipur products are already famous nationwide. Tourists leave; an online store keeps them buying after they go home.', examples: ['Block-print & home textile sellers', 'Gemstone & jewellery dealers', 'Jutti and handicraft makers'] },
  { type: 'city', slug: 'surat', name: 'Surat', state: 'Gujarat', flavor: "Surat is India's textile capital — sarees and dress materials leave the city by the truckload. A storefront lets you sell direct to resellers and end-buyers without a middleman taking margin.", examples: ['Saree & dress material wholesalers', 'Reseller supply businesses', 'Diamond & imitation jewellery'] },
  { type: 'city', slug: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', flavor: 'Chikankari has buyers in every Indian metro and abroad. Lucknow sellers who go online stop depending on showroom footfall and start shipping nationwide.', examples: ['Chikankari boutiques', 'Attar & fragrance houses', 'Kebab masala & food brands'] },
  { type: 'city', slug: 'kanpur', name: 'Kanpur', state: 'Uttar Pradesh', flavor: "Kanpur leather is exported worldwide, yet most local sellers still depend on B2B buyers. A direct-to-customer store captures retail margin the wholesalers keep today.", examples: ['Leather shoe & belt makers', 'Jacket and bag manufacturers', 'Industrial supply traders'] },
  { type: 'city', slug: 'nagpur', name: 'Nagpur', state: 'Maharashtra', flavor: "At India's geographic centre, Nagpur ships everywhere fast. Orange products, snacks and cotton goods from Nagpur reach both coasts in 3–4 days — a real logistics advantage for a new store.", examples: ['Orange & food product brands', 'Cotton garment sellers', 'Spice and condiment makers'] },
  { type: 'city', slug: 'indore', name: 'Indore', state: 'Madhya Pradesh', flavor: "Indore's namkeen and Sarafa-style snacks travel well and sell year-round. Sellers who package well and go online build subscriber-like repeat customers across India.", examples: ['Namkeen & snack brands', 'Sweet shops', 'Fashion and footwear retailers'] },
  { type: 'city', slug: 'bhopal', name: 'Bhopal', state: 'Madhya Pradesh', flavor: 'Zardozi work, batua bags and handicrafts from Bhopal carry stories buyers love. An online store with good photos turns that craft into orders from metros.', examples: ['Zardozi & embroidery artisans', 'Handicraft sellers', 'Home decor makers'] },
  { type: 'city', slug: 'patna', name: 'Patna', state: 'Bihar', flavor: 'Madhubani art, handloom and sattu-based foods — Bihar products have growing national pride behind them. Patna sellers going online ride that wave directly.', examples: ['Madhubani artists', 'Handloom weavers', 'Regional food brands'] },
  { type: 'city', slug: 'ludhiana', name: 'Ludhiana', state: 'Punjab', flavor: "Ludhiana is India's hosiery capital — winter wear from here stocks shops nationwide. Direct online sales mean your brand, your prices, your customer list instead of a label sewn for someone else.", examples: ['Hosiery & knitwear manufacturers', 'Winter wear brands', 'Sports goods sellers'] },
  { type: 'city', slug: 'agra', name: 'Agra', state: 'Uttar Pradesh', flavor: 'Petha, marble inlay and a leather shoe industry that shoes half of India — Agra sellers have products tourists ask to ship home. An online store does exactly that.', examples: ['Petha & sweets makers', 'Leather footwear sellers', 'Marble craft artisans'] },
  { type: 'city', slug: 'varanasi', name: 'Varanasi', state: 'Uttar Pradesh', flavor: 'A genuine Banarasi saree is bought for weddings across India and the diaspora. Weavers and showrooms that sell online skip commission agents and ship straight to brides.', examples: ['Banarasi silk weavers', 'Saree showrooms', 'Rudraksha & puja item sellers'] },
  { type: 'city', slug: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', flavor: 'Wet grinders, cotton textiles and jewellery — Kovai products are trusted across South India. Online ordering with COD extends that trust to the whole country.', examples: ['Kitchen appliance dealers', 'Cotton garment makers', 'Jewellery retailers'] },
  { type: 'city', slug: 'kochi', name: 'Kochi', state: 'Kerala', flavor: 'Spices, banana chips and ayurveda from Kerala carry premium trust nationwide. Kochi sellers with an online store ship that trust in a branded box.', examples: ['Spice & tea sellers', 'Ayurvedic product makers', 'Marine & snack food brands'] },
  { type: 'city', slug: 'guwahati', name: 'Guwahati', state: 'Assam', flavor: 'Assam tea, eri and muga silk, bamboo craft — the Northeast has products the rest of India actively searches for. Guwahati sellers online become the gateway.', examples: ['Tea estate brands', 'Eri & muga silk weavers', 'Bamboo and cane craft sellers'] },
  { type: 'city', slug: 'chandigarh', name: 'Chandigarh', state: 'Chandigarh', flavor: 'Phulkari dupattas, boutique fashion and a buyer base with high disposable income — Chandigarh sellers do well online with clean, premium storefronts.', examples: ['Phulkari & boutique sellers', 'Home bakers', 'Fitness and wellness brands'] },
  { type: 'city', slug: 'noida', name: 'Noida', state: 'Uttar Pradesh', flavor: 'Noida is full of first-time D2C founders — accessories, gadgets, print-on-demand. Speed matters here: a store that goes live today beats an agency quote arriving next week.', examples: ['D2C accessory brands', 'Gadget & electronics resellers', 'Print-on-demand creators'] },
  { type: 'city', slug: 'gurgaon', name: 'Gurgaon', state: 'Haryana', flavor: 'Gurgaon brands skew premium — wellness, fashion, curated home goods. Buyers expect polished storefronts, UPI checkout and instant order confirmations.', examples: ['Premium wellness brands', 'Curated home & decor labels', 'Fashion startups'] },
  { type: 'city', slug: 'vadodara', name: 'Vadodara', state: 'Gujarat', flavor: "Vadodara's art-school heritage shows in its sellers: hand-painted goods, designer wear and craft supplies that deserve more than a feed post — they deserve a storefront.", examples: ['Hand-painted decor artists', 'Designer wear boutiques', 'Art & craft supply sellers'] },
  { type: 'city', slug: 'nashik', name: 'Nashik', state: 'Maharashtra', flavor: 'Grapes, raisins and farm produce from Nashik reach metro kitchens already — sellers with their own store keep the margin that aggregators take.', examples: ['Farm produce & dry fruit sellers', 'Winery-adjacent gift brands', 'Religious & puja item sellers'] },
  { type: 'city', slug: 'rajkot', name: 'Rajkot', state: 'Gujarat', flavor: "Rajkot's imitation jewellery supplies half of India's retail counters. Selling direct online means reseller orders at wholesale volume plus retail buyers at full margin.", examples: ['Imitation jewellery makers', 'Silverware sellers', 'Kitchenware manufacturers'] },
  { type: 'city', slug: 'madurai', name: 'Madurai', state: 'Tamil Nadu', flavor: 'Sungudi cotton sarees, malli poo and temple-town trust — Madurai sellers have heritage products that buyers across Tamil Nadu and beyond order again and again.', examples: ['Sungudi & cotton saree sellers', 'Flower and puja suppliers', 'Snack and sweet makers'] },
  { type: 'city', slug: 'amritsar', name: 'Amritsar', state: 'Punjab', flavor: 'Phulkari, papad-wadiyan and juttis from Amritsar are bought by Punjabi families worldwide. An online store with COD and UPI turns that diaspora demand into daily orders.', examples: ['Phulkari & jutti sellers', 'Papad-wadiyan food brands', 'Religious goods sellers'] },
]

export const CATEGORY_PAGES: CategoryPage[] = [
  { type: 'category', slug: 'sarees', name: 'Sarees', noun: 'saree store', flavor: 'Saree buyers research on Instagram but hesitate to pay strangers via DM. A storefront with photos, prices and COD converts that hesitation into orders — especially during wedding season.', examples: ['Banarasi, Kanjivaram & silk sarees', 'Daily-wear cotton & tant', 'Designer and party-wear collections'] },
  { type: 'category', slug: 'kirana-grocery', name: 'Kirana & Grocery', noun: 'kirana store', flavor: 'Your regular customers already WhatsApp you their lists. An online kirana store turns those messages into structured orders with payment done — no more notebook khata for deliveries.', examples: ['Daily staples & packaged goods', 'Local & regional specialties', 'Monthly ration bundles'] },
  { type: 'category', slug: 'jewellery', name: 'Jewellery', noun: 'jewellery store', flavor: 'From imitation sets to silver and gemstones, jewellery is among the highest-margin categories online. Good photos plus COD trust is the entire formula.', examples: ['Imitation & oxidised sets', 'Silver and gemstone pieces', 'Bridal and occasion collections'] },
  { type: 'category', slug: 'clothing-boutique', name: 'Boutique Clothing', noun: 'boutique', flavor: 'Boutiques live on repeat customers. An online store gives your regulars a place to browse new stock the moment you post it — and lets a WhatsApp status drive checkouts overnight.', examples: ['Designer kurtis & suits', 'Stitched & semi-stitched wear', 'Kids and family collections'] },
  { type: 'category', slug: 'mobile-accessories', name: 'Mobile Accessories', noun: 'accessories store', flavor: 'Cases, chargers, earphones — small parcels, fast shipping, high repeat rates. Accessories sellers scale on volume, and an online store handles 100 orders as easily as 10.', examples: ['Cases & covers', 'Chargers, cables & power banks', 'Earphones and smart accessories'] },
  { type: 'category', slug: 'home-decor', name: 'Home Decor', noun: 'decor store', flavor: 'Decor buyers shop by mood and photo. A clean storefront with collections — wall, table, lighting — sells far better than a cluttered marketplace listing buried among thousands.', examples: ['Wall art & hangings', 'Table decor and lighting', 'Festive and seasonal collections'] },
  { type: 'category', slug: 'handicrafts', name: 'Handicrafts', noun: 'handicraft store', flavor: 'Handmade products carry stories mass marketplaces flatten. Your own store lets you tell the craft, the maker and the region — and charge what the work is actually worth.', examples: ['Regional craft & folk art', 'Handwoven textiles', 'Eco-friendly and bamboo products'] },
  { type: 'category', slug: 'ayurveda-wellness', name: 'Ayurveda & Wellness', noun: 'wellness store', flavor: 'Wellness buyers are loyal repeat customers — once they trust a brand, they reorder monthly. A branded store with GST invoices builds exactly that trust.', examples: ['Ayurvedic oils & supplements', 'Herbal teas and powders', 'Skin and hair care'] },
  { type: 'category', slug: 'bakery-sweets', name: 'Bakery & Sweets', noun: 'bakery store', flavor: 'Home bakers and halwais lose orders to back-and-forth DMs every festival. A store with a menu, prices and delivery slots captures the Diwali rush instead of drowning in it.', examples: ['Cakes & custom bakes', 'Traditional mithai boxes', 'Festival hampers and gifting'] },
  { type: 'category', slug: 'footwear', name: 'Footwear', noun: 'footwear store', flavor: 'Juttis, sneakers, formal pairs — footwear sells online when size charts are clear and returns feel safe. Set both once, then let WhatsApp shares do the marketing.', examples: ['Ethnic juttis & kolhapuris', 'Casual and sports shoes', 'Kids and seasonal footwear'] },
  { type: 'category', slug: 'beauty-cosmetics', name: 'Beauty & Cosmetics', noun: 'beauty store', flavor: 'Beauty thrives on reels and recommendations. The sellers who win attach a real checkout to that content — viewers buy in the moment or not at all.', examples: ['Makeup and skincare', 'Organic and handmade products', 'Salon-grade professional supplies'] },
  { type: 'category', slug: 'books-stationery', name: 'Books & Stationery', noun: 'stationery store', flavor: 'Exam guides, art supplies, planners — stationery has steady year-round demand with school-season spikes. Online ordering with COD wins parent trust instantly.', examples: ['School and exam books', 'Art and craft supplies', 'Planners, journals and gifts'] },
  { type: 'category', slug: 'toys-games', name: 'Toys & Games', noun: 'toy store', flavor: 'Parents buy toys online late at night after kids sleep. A storefront with age filters and COD catches purchases a physical shop never sees.', examples: ['Educational and STEM toys', 'Board games and puzzles', 'Soft toys and gifting'] },
  { type: 'category', slug: 'organic-food', name: 'Organic Food', noun: 'organic store', flavor: 'Organic buyers read labels and reorder weekly. Your own store builds the subscription-like habit that marketplace listings, sandwiched between cheaper fakes, never can.', examples: ['Cold-pressed oils & ghee', 'Millets, grains and flours', 'Honey, pickles and preserves'] },
  { type: 'category', slug: 'pickles-masalas', name: 'Pickles & Masalas', noun: 'food store', flavor: "Ghar ka achaar and family masala recipes have buyers far from home — students, NRIs, nostalgic metro families. Small jars ship cheap and reorder rates are the best in food.", examples: ['Homemade pickles & chutneys', 'Ground spice blends', 'Podi, papad and preserves'] },
]

export type SeoPage = CityPage | CategoryPage

export const ALL_SEO_PAGES: SeoPage[] = [...CITY_PAGES, ...CATEGORY_PAGES]

export function getSeoPage(slug: string): SeoPage | undefined {
  return ALL_SEO_PAGES.find(p => p.slug === slug)
}
