import { NextResponse } from 'next/server'

/**
 * Versioned content for Nyaya's "Know Your Rights" tab. The app fetches this on
 * launch, compares `version` to its locally cached copy, and only downloads/replaces
 * the local copy if this version is newer — so content can be corrected/expanded
 * without an app store release. If the fetch fails (offline, etc.), the app falls
 * back to the bundled copy it ships with, so it stays fully usable offline.
 *
 * Bump `version` and `lastUpdated` on every content change. Keep this file the
 * source of truth going forward — the Kotlin app's bundled copy (KnowYourRights.kt)
 * is the offline fallback/seed and should be updated to match on major app releases,
 * but does not need to change for routine content fixes — those ship here instead.
 */
const DATA = {
  version: 1,
  lastUpdated: '2026-07-04',
  emergencyNumbers: [
    { name: 'Police / All Emergencies', number: '112', whenToUse: 'Any emergency — police, fire, ambulance' },
    { name: "Women's Helpline", number: '181', whenToUse: 'Domestic violence, harassment, any distress' },
    { name: 'Child Helpline', number: '1098', whenToUse: 'Any child in danger or needing help' },
    { name: 'Cyber Crime Helpline', number: '1930', whenToUse: 'Online/UPI/financial fraud — call within the first hour if possible' },
    { name: 'National Consumer Helpline', number: '1915', whenToUse: 'Product/service complaints (WhatsApp: +91 8800001915)' },
    { name: 'Free Legal Aid (NALSA)', number: '15100', whenToUse: "Free lawyer/legal help if you can't afford one" },
    { name: 'Senior Citizen Helpline', number: '14567', whenToUse: 'Elder abuse, neglect, or elder care distress' },
  ],
  officialDirectories: [
    { name: 'Find your District Legal Services Authority (free legal aid)', url: 'https://nalsa.gov.in/lsams/' },
    { name: 'State/UT Consumer Commission directory', url: 'https://edaakhil.nic.in/' },
    { name: 'Cyber Crime Portal (report + track)', url: 'https://cybercrime.gov.in/' },
    { name: 'State RERA authority directory', url: 'https://rera.gov.in/' },
    { name: 'India Code — bare acts and statutes', url: 'https://www.indiacode.nic.in/' },
  ],
  situations: [
    {
      id: 'traffic_key_seized', title: 'Traffic police took my bike/car key', category: 'POLICE_SAFETY',
      tags: ['traffic police', 'key seized', 'bike key', 'car key', 'vehicle stopped', 'challan', 'license taken'],
      simpleExplanation: "Police give you a ticket (challan) for breaking a traffic rule — they don't get to just take your key and keep it.",
      summary: 'Police cannot arbitrarily confiscate your vehicle key. If you\'re being fined (challaned), the process is a challan, not key seizure.',
      steps: [
        "Ask which specific offence you're being fined for, and ask to see the officer's ID card — every traffic police officer must show ID on request.",
        'A traffic offence is normally handled via an e-challan (SMS/app-based) or a physical challan — your vehicle or key should not be seized for ordinary offences like a missing document or a signal jump.',
        "If a document (RC, insurance, PUC, driving licence) is genuinely missing/expired, that's a specific finable offence — ask for the exact provision and challan receipt.",
        "You can pay the challan later online (state e-challan portal / Parivahan) in most cases — you're not obligated to pay cash on the spot unless it's a compoundable on-the-spot fine with a receipt.",
        'If the key or vehicle is physically withheld beyond issuing a challan, note the officer\'s name/ID, location, time, and ask for a written reason.',
        'You can complain to the local traffic police station or the Superintendent/Commissioner\'s office if a key or vehicle was improperly withheld.',
      ],
      whereToGo: 'Nearest traffic police station, or state Traffic Police helpline / e-challan portal (state Parivahan site).',
      documentsToCarry: ['Driving licence', 'RC (registration certificate)', 'Insurance', 'PUC certificate'],
      emergency: false,
    },
    {
      id: 'police_stop_search', title: 'Police want to stop and search me', category: 'POLICE_SAFETY',
      tags: ['police search', 'stopped by police', 'frisking', 'checkpost'],
      simpleExplanation: 'Police can ask to check you, but they must tell you why, and a woman can only be searched by another woman.',
      summary: 'You have the right to know why you\'re being stopped, and searches of a person generally require reasonable grounds.',
      steps: [
        "Ask the officer for their name and ID — you're entitled to see it.",
        'Ask the reason for the stop/search.',
        'A search of a woman must be conducted only by another woman, with strict regard to decency (Section 51, BNSS 2023).',
        'You can ask to be taken to the nearest police station if you believe the stop is unjustified, though cooperate calmly in the moment.',
        'Note down the time, place, and officer details if you plan to file a complaint afterward.',
      ],
      whereToGo: 'File a written complaint to the Station House Officer (SHO), or the Superintendent of Police / Commissioner.',
      documentsToCarry: ['Any government ID, if you have one on you'],
      emergency: false,
    },
    {
      id: 'arrested_rights', title: "I'm being arrested — what are my rights?", category: 'POLICE_SAFETY',
      tags: ['arrest', 'detained', 'police custody', 'fir against me'],
      simpleExplanation: 'If police arrest you, they must tell you why, let you inform someone, and take you to a judge within 24 hours.',
      summary: 'Arrested persons have specific, well-established rights under Indian law (BNSS 2023, mirroring old CrPC protections and DK Basu guidelines).',
      steps: [
        'You have the right to know the grounds of your arrest immediately.',
        'You have the right to inform a friend, relative, or any person of your choice about the arrest and where you\'re being held (Section 48, BNSS 2023).',
        'You must be produced before a magistrate within 24 hours of arrest (excluding travel time) — Article 22(2) of the Constitution, Section 58 BNSS 2023.',
        'You have the right to consult a lawyer of your choice, and to have one present during interrogation in many circumstances.',
        'For a bailable offence, you have the right to be released on bail.',
        'You cannot be subjected to unnecessary restraint (handcuffing) except in specific circumstances defined by law.',
        'Ask for a copy of the arrest memo, attested by a witness, with the time and date of arrest.',
      ],
      whereToGo: 'Contact a criminal lawyer immediately, or the nearest Legal Services Authority — call 15100 for free legal aid.',
      documentsToCarry: ['Any ID you have', 'Contact number of a lawyer or family member'],
      emergency: true,
    },
    {
      id: 'fir_refused', title: 'Police are refusing to file my FIR', category: 'POLICE_SAFETY',
      tags: ['fir refused', 'police not registering complaint', 'cognizable offence'],
      simpleExplanation: 'For serious crimes, police must write down your complaint (FIR) — if they refuse, you can go over their head.',
      summary: 'For a cognizable offence, police are legally required to register an FIR — refusal has specific escalation routes.',
      steps: [
        'For a cognizable offence (serious crimes like theft, assault, etc.), police must register an FIR — Section 173, BNSS 2023.',
        'Submit your complaint in writing and ask for an acknowledgment/receipt.',
        'If refused, send the complaint in writing by post to the Superintendent of Police (SP), who must investigate or direct a subordinate to.',
        'You can also approach the Judicial Magistrate under Section 175(3), BNSS 2023, to direct police to register the FIR.',
        'For some cognizable-but-minor matters, police may first do a preliminary inquiry before registering an FIR — ask which applies to your case.',
      ],
      whereToGo: 'Superintendent of Police (SP) office in writing, or file an application before the Judicial Magistrate.',
      documentsToCarry: ['Written complaint copy', 'Any evidence you have (photos, messages, witness details)'],
      emergency: false,
    },
    {
      id: 'landlord_deposit_not_returned', title: 'Landlord not returning my security deposit', category: 'HOME_RENT',
      tags: ['rent deposit', 'landlord not paying', 'tenant rights'],
      simpleExplanation: 'Your landlord cannot keep your deposit without a valid reason. Ask in writing first, then escalate if ignored.',
      summary: 'Most rent agreements require deposit return at vacation, minus legitimate deductions — non-return has a clear escalation path.',
      steps: [
        'Check your rent agreement for the deposit return clause and timeline.',
        "Send a written demand (legal notice) to the landlord asking for deposit return, listing the amount and date vacated. Use this app's Legal Notice draft.",
        'Keep evidence: photos of the property condition at move-out, the rent agreement, payment receipts, and any chats/emails.',
        "If the landlord doesn't respond, you can file with the Rent Court / Rent Controller (if your state has one) or a civil recovery suit.",
        'For smaller amounts, small causes courts or consumer forums may be an option depending on your state — a local advocate can confirm the right forum.',
      ],
      whereToGo: 'Rent Controller / Rent Court (if applicable in your state) or the appropriate Civil Court; send a legal notice first.',
      documentsToCarry: ['Rent agreement', 'Payment receipts', 'Move-out photos/evidence'],
      emergency: false,
    },
    {
      id: 'tenant_harassment', title: 'My landlord is harassing or threatening me', category: 'HOME_RENT',
      tags: ['landlord harassment', 'eviction threat', 'illegal eviction', 'landlord threatening'],
      simpleExplanation: 'A landlord cannot force you out, cut your power/water, or threaten you — eviction has to go through the proper process.',
      summary: 'Landlords cannot evict tenants forcibly or cut essential services — proper legal process must be followed even for a rule-breaking tenant.',
      steps: [
        "A landlord cannot forcibly remove you, change locks, or cut water/electricity to force you out — this is illegal 'self-help eviction' in most states.",
        'Document every incident: date, what happened, photos/videos, witnesses.',
        "Send a written response if you receive any eviction notice, and check if it follows your state's Rent Control Act procedure.",
        'If services are cut off illegally, you can file a police complaint and approach the Rent Controller / Civil Court for restoration.',
        'For threats or intimidation, you can file a police complaint separately from the tenancy dispute.',
      ],
      whereToGo: 'Local police station for threats/illegal cut-offs; Rent Controller or Civil Court for the tenancy dispute itself.',
      documentsToCarry: ['Rent agreement', 'Photos/videos of incidents', 'Any written threats/messages'],
      emergency: false,
    },
    {
      id: 'salary_unpaid', title: "My employer hasn't paid my salary", category: 'WORK',
      tags: ['salary not paid', 'unpaid wages', 'employer not paying'],
      simpleExplanation: "If your employer doesn't pay you, you can complain to the Labour Department — it's usually faster than going to court.",
      summary: 'Unpaid wages have a specific, fast-track legal remedy through the Labour authorities, separate from a civil suit.',
      steps: [
        'Send a written demand to your employer/HR for the unpaid salary, keeping a copy.',
        'If unresolved, file a complaint with the Labour Commissioner / Labour Officer in your area — usually faster and cheaper than civil court.',
        'For claims within limits under the Payment of Wages Act, 1936, approach the designated Authority under that Act.',
        'Keep your appointment letter, salary slips, attendance records, and any written acknowledgment of dues as evidence.',
        "If terminated without dues clearance, note the termination date — there are limitation periods for filing claims, so don't delay.",
      ],
      whereToGo: 'Office of the Labour Commissioner (state or central, depending on the employer), or the Authority under the Payment of Wages Act.',
      documentsToCarry: ['Appointment letter', 'Salary slips', 'Attendance records', 'Any written dues acknowledgment'],
      emergency: false,
    },
    {
      id: 'sudden_termination', title: 'My employer fired me suddenly, with no notice', category: 'WORK',
      tags: ['fired suddenly', 'terminated without notice', 'wrongful termination', 'no notice period'],
      simpleExplanation: 'Most jobs need proper notice or notice-pay before firing you — a sudden firing with none may not be lawful.',
      summary: 'Termination rules depend on your employment contract, notice period, and applicable labour law — check what you were owed.',
      steps: [
        'Check your appointment letter / contract for the required notice period or notice pay in lieu.',
        'Ask for the termination letter in writing, stating the reason.',
        "If you were denied notice pay, full and final settlement, or dues, send a written demand first.",
        "You can file a complaint with the Labour Commissioner if dues aren't paid, or explore an industrial dispute route if you're a 'workman' under labour law — a labour lawyer can confirm.",
        'Keep your appointment letter, any termination communication, and salary history as evidence.',
      ],
      whereToGo: "Labour Commissioner's office; consult a labour lawyer to check if industrial dispute remedies apply to your role.",
      documentsToCarry: ['Appointment letter/contract', 'Termination letter or messages', 'Salary slips'],
      emergency: false,
    },
    {
      id: 'defective_product', title: 'I received a defective product or bad service', category: 'MONEY_SHOPPING',
      tags: ['defective product', 'bad service', 'refund refused', 'consumer complaint'],
      simpleExplanation: 'If something you bought is broken or the service was bad, you can demand a refund — and complain officially if refused.',
      summary: 'Consumer Protection Act 2019 gives you a clear complaint path for defective goods or deficient services.',
      steps: [
        'First raise the issue with the seller/service provider in writing (email/WhatsApp) and ask for refund/replacement/repair, keeping records.',
        'If unresolved, file a complaint with the National Consumer Helpline (1915) or on the government\'s e-daakhil portal.',
        "For formal complaints, file before the District Consumer Disputes Redressal Commission — this app's Drafts tab has a Consumer Complaint template.",
        'Complaints must generally be filed within 2 years of the cause of action (Section 69, Consumer Protection Act 2019).',
        'Keep the purchase invoice/receipt, product photos, and all communication with the seller as evidence.',
      ],
      whereToGo: 'National Consumer Helpline (1915) or e-daakhil.nic.in, then the District Consumer Disputes Redressal Commission if unresolved.',
      documentsToCarry: ['Purchase invoice/receipt', 'Photos of the defect', 'Communication with seller'],
      emergency: false,
    },
    {
      id: 'loan_recovery_harassment', title: 'Loan recovery agents are harassing me', category: 'MONEY_SHOPPING',
      tags: ['loan recovery harassment', 'recovery agent threat', 'loan app harassment'],
      simpleExplanation: "Recovery agents can ask you to pay, but they can't threaten, abuse, or harass you or your family — that crosses into illegal territory.",
      summary: 'RBI rules and criminal law both restrict how recovery agents can behave — harassment and threats are not lawful collection tactics.',
      steps: [
        'You can owe a genuine debt and still have rights — recovery agents cannot use threats, abuse, public shaming, or contact your employer/family to intimidate you (RBI Fair Practices Code for lenders).',
        'Document every call/message: date, time, what was said, and by whom.',
        "Send a written complaint to the lender's grievance officer, referencing RBI's Fair Practices Code.",
        'If unresolved, complain to the RBI Banking Ombudsman (for banks/NBFCs) or file a police complaint for threats/harassment/criminal intimidation.',
        'For unlicensed loan apps, report to the Cyber Crime Helpline 1930 as well, since many operate fraudulently.',
      ],
      whereToGo: "Lender's grievance officer, then RBI Banking Ombudsman (cms.rbi.org.in); police for threats; 1930 for unlicensed loan-app fraud.",
      documentsToCarry: ['Call/message records', 'Loan agreement', 'Complaint correspondence'],
      emergency: false,
    },
    {
      id: 'cheque_bounced', title: 'A cheque given to me has bounced', category: 'MONEY_SHOPPING',
      tags: ['cheque bounce', 'cheque dishonour', 'payment bounced'],
      simpleExplanation: 'A bounced cheque is a crime in India, but you must send a demand notice fast — the deadlines are strict.',
      summary: 'Cheque dishonour is a specific criminal offence under the Negotiable Instruments Act with strict, short timelines — act quickly.',
      steps: [
        'You must issue a legal notice to the cheque issuer within 30 days of receiving the bank\'s dishonour memo, demanding payment (Section 138, Negotiable Instruments Act, 1881).',
        'The issuer then has 15 days from receiving your notice to pay.',
        "If they don't pay within that 15-day window, you can file a criminal complaint within 30 days after that window closes.",
        'Keep the original cheque, the bank\'s return memo, and proof of sending the legal notice as your core evidence.',
        "This app's Drafts tab has a Legal Notice template you can adapt — a lawyer should review the criminal complaint itself.",
      ],
      whereToGo: "Send legal notice immediately, then file a criminal complaint before the Magistrate's court with jurisdiction, within the timelines above.",
      documentsToCarry: ['Original bounced cheque', 'Bank return/dishonour memo', 'Proof of notice delivery'],
      emergency: false,
    },
    {
      id: 'cyber_fraud', title: "I've been a victim of online/cyber fraud", category: 'ONLINE_SAFETY',
      tags: ['cyber fraud', 'online scam', 'upi fraud', 'hacked account'],
      simpleExplanation: 'If someone steals your money online, call 1930 right now — the first hour matters most for getting it back.',
      summary: 'Cybercrime has a dedicated, time-sensitive national reporting system — report immediately, especially for financial fraud.',
      steps: [
        'For financial fraud, call the Cyber Crime Helpline 1930 immediately — banks can sometimes freeze/reverse a fraudulent transaction if reported within a golden window (often the first few hours).',
        'File a detailed complaint at cybercrime.gov.in with transaction IDs, screenshots, and timestamps.',
        'Also inform your bank in writing to block further transactions and request a freeze on the receiving account if possible.',
        'Keep all screenshots, SMS/email alerts, and transaction reference numbers — do not delete anything.',
        "You can also file an FIR at your local police station's cybercrime cell for serious cases.",
      ],
      whereToGo: 'Cyber Crime Helpline 1930, cybercrime.gov.in, and your bank\'s fraud reporting line.',
      documentsToCarry: ['Transaction screenshots', 'Bank statements', 'Any communication with the fraudster'],
      emergency: true,
    },
    {
      id: 'domestic_violence', title: "I'm facing domestic violence or family abuse", category: 'FAMILY_SAFETY',
      tags: ['domestic violence', 'abuse at home', 'family abuse', 'women safety'],
      simpleExplanation: "You don't have to stay in danger. Call 181 or 112 immediately — there is a specific law that protects you, with fast protection orders.",
      summary: 'The Protection of Women from Domestic Violence Act, 2005 gives fast, practical remedies — protection orders, residence rights, and monetary relief.',
      steps: [
        'If you\'re in immediate danger, call 112 (police) or 181 (Women\'s Helpline) right now.',
        'You can approach a Protection Officer (appointed in every district) or file directly before a Magistrate under the Domestic Violence Act, 2005.',
        'The law covers physical, emotional, verbal, sexual, and economic abuse, and applies to women in a domestic/family relationship, not just marriage.',
        'You can get a Protection Order (stops further abuse), a Residence Order (right to stay in the shared household), and monetary relief — often quickly.',
        'Document incidents when it\'s safe to do so: photos of injuries, messages, medical records, witness details.',
        "Free legal aid is available — call NALSA at 15100 if you can't afford a lawyer.",
      ],
      whereToGo: 'Call 112 or 181 for immediate danger. District Protection Officer or Magistrate\'s Court for legal remedies. NALSA 15100 for free legal aid.',
      documentsToCarry: ['Any medical records', 'Photos/messages if safely collected', 'ID proof'],
      emergency: true,
    },
    {
      id: 'harassment_threats', title: 'Someone is harassing or threatening me', category: 'FAMILY_SAFETY',
      tags: ['harassment', 'threats', 'stalking', 'intimidation'],
      simpleExplanation: "Threats and harassment are crimes, even if no one has been physically hurt yet — you can report it to police.",
      summary: 'Criminal intimidation, stalking, and harassment are cognizable offences under the Bharatiya Nyaya Sanhita, 2023.',
      steps: [
        'If you\'re in immediate danger, call 112.',
        'Save all evidence: messages, call logs, screenshots, voice notes — do not delete anything, even if upsetting.',
        'File a written police complaint describing the incidents with dates; for a cognizable offence, police must register an FIR.',
        "For stalking or harassment specifically targeting women, mention this explicitly — it's a distinct offence with its own provisions.",
        'You can also request a restraining/protection order through the court if the threats continue.',
      ],
      whereToGo: "Local police station (call 112 for immediate danger); Women's Helpline 181 if applicable.",
      documentsToCarry: ['Screenshots/messages/call logs', 'Written timeline of incidents'],
      emergency: true,
    },
    {
      id: 'builder_delay', title: 'My builder is delaying my flat/property possession', category: 'HOME_RENT',
      tags: ['builder delay', 'property possession delay', 'rera complaint', 'flat delay'],
      simpleExplanation: 'If your builder promised a date and missed it, you can complain to RERA — a special authority just for real estate problems.',
      summary: 'The Real Estate (Regulation and Development) Act, 2016 (RERA) gives buyers a dedicated, faster complaint route against builders.',
      steps: [
        'Check your Agreement for Sale for the promised possession date.',
        'Send a written notice to the builder demanding possession or compensation for delay.',
        "If unresolved, file a complaint with your state's RERA (Real Estate Regulatory Authority) — most states have an online portal for this.",
        'RERA can order the builder to pay interest for the delay period, or in some cases refund with interest.',
        'Keep your booking receipt, Agreement for Sale, payment records, and all communication with the builder.',
      ],
      whereToGo: "State RERA authority (search '[your state] RERA' for the official portal).",
      documentsToCarry: ['Agreement for Sale', 'Payment receipts', 'Builder communication'],
      emergency: false,
    },
    {
      id: 'hospital_negligence', title: 'I suspect medical/hospital negligence', category: 'MONEY_SHOPPING',
      tags: ['medical negligence', 'hospital negligence', 'doctor negligence', 'wrong treatment'],
      simpleExplanation: 'If a hospital or doctor was careless and it hurt you, you can complain — but this needs medical evidence, so start collecting records now.',
      summary: 'Medical negligence claims are fact-heavy and require expert medical opinion — start by securing your records immediately.',
      steps: [
        'Request certified copies of your complete medical records from the hospital in writing — you have a right to these.',
        'Consult another doctor for a second/independent medical opinion on what happened.',
        'You can file a complaint with the State Medical Council (against the doctor) and/or a consumer complaint (treatment as a paid service) before the Consumer Commission.',
        'For serious harm, a criminal complaint may also be an option, but courts require clear proof of negligence, not just a bad outcome — consult a lawyer experienced in medical cases.',
        "Time limits apply (2 years for consumer complaints from when you knew of the negligence) — don't delay collecting records.",
      ],
      whereToGo: 'State Medical Council (professional complaint); Consumer Commission for compensation; a lawyer for a criminal complaint.',
      documentsToCarry: ['Complete medical records/discharge summary', 'Bills', 'Second opinion, if obtained'],
      emergency: false,
    },
    {
      id: 'school_college_fee_certificate', title: "School/college won't release my certificates or is overcharging fees", category: 'DOCUMENTS_ADMIN',
      tags: ['certificate withheld', 'school fee issue', 'college not releasing marksheet', 'transfer certificate'],
      simpleExplanation: 'A school or college generally cannot hold back your certificates just because of a fee dispute — most states have rules against this.',
      summary: 'Many states have specific regulations preventing institutions from withholding original certificates over fee disputes.',
      steps: [
        'Send a written request for your certificates/documents, referencing that withholding original certificates over a fee dispute is restricted in most states.',
        "Check your state's Right to Education Act rules (for schools) or the relevant university/UGC regulations (for colleges) on document withholding.",
        'If refused, complain to the District Education Officer (schools) or the university/UGC grievance cell (colleges).',
        'For fee disputes specifically, many states have Fee Regulatory Committees you can approach.',
        'Keep all fee receipts and written correspondence with the institution.',
      ],
      whereToGo: 'District Education Officer (schools); University Grievance Cell / UGC (colleges); state Fee Regulatory Committee for fee disputes.',
      documentsToCarry: ['Fee receipts', 'Admission/enrollment documents', 'Written correspondence'],
      emergency: false,
    },
    {
      id: 'lost_documents', title: "I've lost my important documents (Aadhaar, PAN, etc.)", category: 'DOCUMENTS_ADMIN',
      tags: ['lost documents', 'lost aadhaar', 'lost pan card', 'lost passport'],
      simpleExplanation: 'Losing ID documents is stressful but very fixable — file a police report if needed, then re-apply for each document.',
      summary: 'Each document has its own re-issue process; a police complaint (FIR/lost report) is often useful evidence for reissue and for preventing misuse.',
      steps: [
        'File a lost-property report at the nearest police station or online (many states offer e-FIR/lost-report portals) — useful for reissue and fraud protection.',
        "Aadhaar: retrieve/reprint via UIDAI's website (uidai.gov.in) using your enrollment ID or mobile-linked OTP.",
        'PAN: apply for a reprint/duplicate via the NSDL/UTIITSL portals.',
        'Passport: report loss to local police and the Passport Seva Kendra; a Loss/Damage report is required.',
        "Driving licence: apply for a duplicate via your state's transport department (Parivahan portal).",
        'Consider freezing/monitoring bank accounts if financial documents were also lost, to guard against misuse.',
      ],
      whereToGo: 'Local police station for a lost-property report; then the specific document\'s official portal (UIDAI, NSDL/UTIITSL, Passport Seva, Parivahan).',
      documentsToCarry: ['Any remaining ID proof', 'Photocopies of lost documents, if you have any'],
      emergency: false,
    },
    {
      id: 'rti_filing', title: 'I want to ask the government for information (RTI)', category: 'DOCUMENTS_ADMIN',
      tags: ['rti', 'right to information', 'government information request'],
      simpleExplanation: 'You can formally ask any government office a question and they must answer within 30 days — this is called an RTI.',
      summary: 'The Right to Information Act, 2005 lets any citizen request information from a public authority, with a mandatory 30-day response window.',
      steps: [
        'Identify the exact public authority that holds the information you want.',
        "Write a specific, point-wise application addressed to the Public Information Officer (PIO) of that authority — this app's Drafts tab has an RTI Application template.",
        'Pay the prescribed fee (usually ₹10, via postal order/online as per that authority\'s process).',
        'The authority must respond within 30 days (48 hours for information concerning life or liberty).',
        'If denied or ignored, you can file a First Appeal with the authority\'s Appellate Authority, then a Second Appeal with the State/Central Information Commission.',
      ],
      whereToGo: 'The Public Information Officer (PIO) of the relevant department; escalate to the Information Commission if needed.',
      documentsToCarry: ['Filled RTI application', 'Fee payment proof'],
      emergency: false,
    },
    {
      id: 'free_legal_aid', title: "I can't afford a lawyer — can I get free help?", category: 'DOCUMENTS_ADMIN',
      tags: ['free legal aid', 'cannot afford lawyer', 'nalsa', 'legal aid eligibility'],
      simpleExplanation: "If you can't afford a lawyer, the government gives you one for free — just call 15100.",
      summary: 'NALSA (National Legal Services Authority) provides free legal aid to eligible categories, including women, children, SC/ST, and low-income individuals.',
      steps: [
        'Call the NALSA helpline 15100, or visit your nearest District Legal Services Authority (DLSA).',
        'Free legal aid is generally available to: women, children, SC/ST persons, industrial workmen, disaster/violence victims, persons with disabilities, and those with annual income below the state-specified limit.',
        "You'll typically need basic ID proof and a brief description of your legal issue.",
        'DLSA can provide a lawyer, help with drafting, and represent you in court proceedings, often at no cost.',
        'Law school legal aid clinics in your city may also offer free consultations.',
      ],
      whereToGo: "NALSA helpline 15100, or your District Legal Services Authority (DLSA) — search 'DLSA [your district]' for local contact.",
      documentsToCarry: ['Any ID proof', 'Income proof, if applicable', 'Brief written description of your issue'],
      emergency: false,
    },
  ],
}

export async function GET() {
  return NextResponse.json(DATA, {
    headers: {
      'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
    },
  })
}
