import { NextResponse } from 'next/server'

/**
 * Versioned content for Nyaya's "Know Your Rights" tab. The app fetches this on
 * launch, compares `version` to its locally cached copy, and only downloads/replaces
 * the local copy if this version is newer — so content can be corrected/expanded
 * without an app store release. If the fetch fails (offline, etc.), the app falls
 * back to the bundled copy it ships with, so it stays fully usable offline.
 *
 * Bump `version` and `lastUpdated` on every content change. Keep this file the
 * source of truth going forward — the Kotlin app's bundled copy (KnowYourRights.kt)
 * is the offline fallback/seed and should be updated to match on major app releases,
 * but does not need to change for routine content fixes — those ship here instead.
 */
const DATA = {
  version: 3,
  lastUpdated: '2026-07-04',
  emergencyNumbers: [
    { name: 'Police / All Emergencies', number: '112', whenToUse: 'Any emergency — police, fire, ambulance' },
    { name: "Women's Helpline", number: '181', whenToUse: 'Domestic violence, harassment, any distress' },
    { name: 'Child Helpline', number: '1098', whenToUse: 'Any child in danger or needing help' },
    { name: 'Cyber Crime Helpline', number: '1930', whenToUse: 'Online/UPI/financial fraud — call within the first hour if possible' },
    { name: 'National Consumer Helpline', number: '1915', whenToUse: 'Product/service complaints (WhatsApp: +91 8800001915)' },
    { name: 'Free Legal Aid (NALSA)', number: '15100', whenToUse: "Free lawyer/legal help if you can't afford one" },
    { name: 'Senior Citizen Helpline', number: '14567', whenToUse: 'Elder abuse, neglect, or elder care distress' },
  ],
  officialDirectories: [
    { name: 'Find your District Legal Services Authority (free legal aid)', url: 'https://nalsa.gov.in/lsams/' },
    { name: 'State/UT Consumer Commission directory', url: 'https://edaakhil.nic.in/' },
    { name: 'Cyber Crime Portal (report + track)', url: 'https://cybercrime.gov.in/' },
    { name: 'State RERA authority directory', url: 'https://rera.gov.in/' },
    { name: 'India Code — bare acts and statutes', url: 'https://www.indiacode.nic.in/' },
  ],
  situations: [
    {
      id: 'traffic_key_seized', title: 'Traffic police took my bike/car key', category: 'POLICE_SAFETY',
      tags: ['traffic police', 'key seized', 'bike key', 'car key', 'vehicle stopped', 'challan', 'license taken'],
      simpleExplanation: "Police give you a ticket (challan) for breaking a traffic rule — they don't get to just take your key and keep it.",
      summary: 'Police cannot arbitrarily confiscate your vehicle key. If you\'re being fined (challaned), the process is a challan, not key seizure.',
      steps: [
        "Ask which specific offence you're being fined for, and ask to see the officer's ID card — every traffic police officer must show ID on request.",
        'A traffic offence is normally handled via an e-challan (SMS/app-based) or a physical challan — your vehicle or key should not be seized for ordinary offences like a missing document or a signal jump.',
        "If a document (RC, insurance, PUC, driving licence) is genuinely missing/expired, that's a specific finable offence — ask for the exact provision and challan receipt.",
        "You can pay the challan later online (state e-challan portal / Parivahan) in most cases — you're not obligated to pay cash on the spot unless it's a compoundable on-the-spot fine with a receipt.",
        'If the key or vehicle is physically withheld beyond issuing a challan, note the officer\'s name/ID, location, time, and ask for a written reason.',
        'You can complain to the local traffic police station or the Superintendent/Commissioner\'s office if a key or vehicle was improperly withheld.',
      ],
      whereToGo: 'Nearest traffic police station, or state Traffic Police helpline / e-challan portal (state Parivahan site).',
      documentsToCarry: ['Driving licence', 'RC (registration certificate)', 'Insurance', 'PUC certificate'],
      emergency: false,
      officialUrl: 'https://parivahan.gov.in/',
    },
    {
      id: 'police_stop_search', title: 'Police want to stop and search me', category: 'POLICE_SAFETY',
      tags: ['police search', 'stopped by police', 'frisking', 'checkpost'],
      simpleExplanation: 'Police can ask to check you, but they must tell you why, and a woman can only be searched by another woman.',
      summary: 'You have the right to know why you\'re being stopped, and searches of a person generally require reasonable grounds.',
      steps: [
        "Ask the officer for their name and ID — you're entitled to see it.",
        'Ask the reason for the stop/search.',
        'A search of a woman must be conducted only by another woman, with strict regard to decency (Section 51, BNSS 2023).',
        'You can ask to be taken to the nearest police station if you believe the stop is unjustified, though cooperate calmly in the moment.',
        'Note down the time, place, and officer details if you plan to file a complaint afterward.',
      ],
      whereToGo: 'File a written complaint to the Station House Officer (SHO), or the Superintendent of Police / Commissioner.',
      documentsToCarry: ['Any government ID, if you have one on you'],
      emergency: false,
    },
    {
      id: 'arrested_rights', title: "I'm being arrested — what are my rights?", category: 'POLICE_SAFETY',
      tags: ['arrest', 'detained', 'police custody', 'fir against me'],
      simpleExplanation: 'If police arrest you, they must tell you why, let you inform someone, and take you to a judge within 24 hours.',
      summary: 'Arrested persons have specific, well-established rights under Indian law (BNSS 2023, mirroring old CrPC protections and DK Basu guidelines).',
      steps: [
        'You have the right to know the grounds of your arrest immediately.',
        'You have the right to inform a friend, relative, or any person of your choice about the arrest and where you\'re being held (Section 48, BNSS 2023).',
        'You must be produced before a magistrate within 24 hours of arrest (excluding travel time) — Article 22(2) of the Constitution, Section 58 BNSS 2023.',
        'You have the right to consult a lawyer of your choice, and to have one present during interrogation in many circumstances.',
        'For a bailable offence, you have the right to be released on bail.',
        'You cannot be subjected to unnecessary restraint (handcuffing) except in specific circumstances defined by law.',
        'Ask for a copy of the arrest memo, attested by a witness, with the time and date of arrest.',
      ],
      whereToGo: 'Contact a criminal lawyer immediately, or the nearest Legal Services Authority — call 15100 for free legal aid.',
      documentsToCarry: ['Any ID you have', 'Contact number of a lawyer or family member'],
      emergency: true,
    },
    {
      id: 'fir_refused', title: 'Police are refusing to file my FIR', category: 'POLICE_SAFETY',
      tags: ['fir refused', 'police not registering complaint', 'cognizable offence'],
      simpleExplanation: 'For serious crimes, police must write down your complaint (FIR) — if they refuse, you can go over their head.',
      summary: 'For a cognizable offence, police are legally required to register an FIR — refusal has specific escalation routes.',
      steps: [
        'For a cognizable offence (serious crimes like theft, assault, etc.), police must register an FIR — Section 173, BNSS 2023.',
        'Submit your complaint in writing and ask for an acknowledgment/receipt.',
        'If refused, send the complaint in writing by post to the Superintendent of Police (SP), who must investigate or direct a subordinate to.',
        'You can also approach the Judicial Magistrate under Section 175(3), BNSS 2023, to direct police to register the FIR.',
        'For some cognizable-but-minor matters, police may first do a preliminary inquiry before registering an FIR — ask which applies to your case.',
      ],
      whereToGo: 'Superintendent of Police (SP) office in writing, or file an application before the Judicial Magistrate.',
      documentsToCarry: ['Written complaint copy', 'Any evidence you have (photos, messages, witness details)'],
      emergency: false,
    },
    {
      id: 'landlord_deposit_not_returned', title: 'Landlord not returning my security deposit', category: 'HOME_RENT',
      tags: ['rent deposit', 'landlord not paying', 'tenant rights'],
      simpleExplanation: 'Your landlord cannot keep your deposit without a valid reason. Ask in writing first, then escalate if ignored.',
      summary: 'Most rent agreements require deposit return at vacation, minus legitimate deductions — non-return has a clear escalation path.',
      steps: [
        'Check your rent agreement for the deposit return clause and timeline.',
        "Send a written demand (legal notice) to the landlord asking for deposit return, listing the amount and date vacated. Use this app's Legal Notice draft.",
        'Keep evidence: photos of the property condition at move-out, the rent agreement, payment receipts, and any chats/emails.',
        "If the landlord doesn't respond, you can file with the Rent Court / Rent Controller (if your state has one) or a civil recovery suit.",
        'For smaller amounts, small causes courts or consumer forums may be an option depending on your state — a local advocate can confirm the right forum.',
      ],
      whereToGo: 'Rent Controller / Rent Court (if applicable in your state) or the appropriate Civil Court; send a legal notice first.',
      documentsToCarry: ['Rent agreement', 'Payment receipts', 'Move-out photos/evidence'],
      emergency: false,
    },
    {
      id: 'tenant_harassment', title: 'My landlord is harassing or threatening me', category: 'HOME_RENT',
      tags: ['landlord harassment', 'eviction threat', 'illegal eviction', 'landlord threatening'],
      simpleExplanation: 'A landlord cannot force you out, cut your power/water, or threaten you — eviction has to go through the proper process.',
      summary: 'Landlords cannot evict tenants forcibly or cut essential services — proper legal process must be followed even for a rule-breaking tenant.',
      steps: [
        "A landlord cannot forcibly remove you, change locks, or cut water/electricity to force you out — this is illegal 'self-help eviction' in most states.",
        'Document every incident: date, what happened, photos/videos, witnesses.',
        "Send a written response if you receive any eviction notice, and check if it follows your state's Rent Control Act procedure.",
        'If services are cut off illegally, you can file a police complaint and approach the Rent Controller / Civil Court for restoration.',
        'For threats or intimidation, you can file a police complaint separately from the tenancy dispute.',
      ],
      whereToGo: 'Local police station for threats/illegal cut-offs; Rent Controller or Civil Court for the tenancy dispute itself.',
      documentsToCarry: ['Rent agreement', 'Photos/videos of incidents', 'Any written threats/messages'],
      emergency: false,
    },
    {
      id: 'salary_unpaid', title: "My employer hasn't paid my salary", category: 'WORK',
      tags: ['salary not paid', 'unpaid wages', 'employer not paying'],
      simpleExplanation: "If your employer doesn't pay you, you can complain to the Labour Department — it's usually faster than going to court.",
      summary: 'Unpaid wages have a specific, fast-track legal remedy through the Labour authorities, separate from a civil suit.',
      steps: [
        'Send a written demand to your employer/HR for the unpaid salary, keeping a copy.',
        'If unresolved, file a complaint with the Labour Commissioner / Labour Officer in your area — usually faster and cheaper than civil court.',
        'For claims within limits under the Payment of Wages Act, 1936, approach the designated Authority under that Act.',
        'Keep your appointment letter, salary slips, attendance records, and any written acknowledgment of dues as evidence.',
        "If terminated without dues clearance, note the termination date — there are limitation periods for filing claims, so don't delay.",
      ],
      whereToGo: 'Office of the Labour Commissioner (state or central, depending on the employer), or the Authority under the Payment of Wages Act.',
      documentsToCarry: ['Appointment letter', 'Salary slips', 'Attendance records', 'Any written dues acknowledgment'],
      emergency: false,
    },
    {
      id: 'sudden_termination', title: 'My employer fired me suddenly, with no notice', category: 'WORK',
      tags: ['fired suddenly', 'terminated without notice', 'wrongful termination', 'no notice period'],
      simpleExplanation: 'Most jobs need proper notice or notice-pay before firing you — a sudden firing with none may not be lawful.',
      summary: 'Termination rules depend on your employment contract, notice period, and applicable labour law — check what you were owed.',
      steps: [
        'Check your appointment letter / contract for the required notice period or notice pay in lieu.',
        'Ask for the termination letter in writing, stating the reason.',
        "If you were denied notice pay, full and final settlement, or dues, send a written demand first.",
        "You can file a complaint with the Labour Commissioner if dues aren't paid, or explore an industrial dispute route if you're a 'workman' under labour law — a labour lawyer can confirm.",
        'Keep your appointment letter, any termination communication, and salary history as evidence.',
      ],
      whereToGo: "Labour Commissioner's office; consult a labour lawyer to check if industrial dispute remedies apply to your role.",
      documentsToCarry: ['Appointment letter/contract', 'Termination letter or messages', 'Salary slips'],
      emergency: false,
    },
    {
      id: 'defective_product', title: 'I received a defective product or bad service', category: 'MONEY_SHOPPING',
      tags: ['defective product', 'bad service', 'refund refused', 'consumer complaint'],
      simpleExplanation: 'If something you bought is broken or the service was bad, you can demand a refund — and complain officially if refused.',
      summary: 'Consumer Protection Act 2019 gives you a clear complaint path for defective goods or deficient services.',
      steps: [
        'First raise the issue with the seller/service provider in writing (email/WhatsApp) and ask for refund/replacement/repair, keeping records.',
        'If unresolved, file a complaint with the National Consumer Helpline (1915) or on the government\'s e-daakhil portal.',
        "For formal complaints, file before the District Consumer Disputes Redressal Commission — this app's Drafts tab has a Consumer Complaint template.",
        'Complaints must generally be filed within 2 years of the cause of action (Section 69, Consumer Protection Act 2019).',
        'Keep the purchase invoice/receipt, product photos, and all communication with the seller as evidence.',
      ],
      whereToGo: 'National Consumer Helpline (1915) or e-daakhil.nic.in, then the District Consumer Disputes Redressal Commission if unresolved.',
      documentsToCarry: ['Purchase invoice/receipt', 'Photos of the defect', 'Communication with seller'],
      emergency: false,
      officialUrl: 'https://edaakhil.nic.in/',
    },
    {
      id: 'loan_recovery_harassment', title: 'Loan recovery agents are harassing me', category: 'MONEY_SHOPPING',
      tags: ['loan recovery harassment', 'recovery agent threat', 'loan app harassment'],
      simpleExplanation: "Recovery agents can ask you to pay, but they can't threaten, abuse, or harass you or your family — that crosses into illegal territory.",
      summary: 'RBI rules and criminal law both restrict how recovery agents can behave — harassment and threats are not lawful collection tactics.',
      steps: [
        'You can owe a genuine debt and still have rights — recovery agents cannot use threats, abuse, public shaming, or contact your employer/family to intimidate you (RBI Fair Practices Code for lenders).',
        'Document every call/message: date, time, what was said, and by whom.',
        "Send a written complaint to the lender's grievance officer, referencing RBI's Fair Practices Code.",
        'If unresolved, complain to the RBI Banking Ombudsman (for banks/NBFCs) or file a police complaint for threats/harassment/criminal intimidation.',
        'For unlicensed loan apps, report to the Cyber Crime Helpline 1930 as well, since many operate fraudulently.',
      ],
      whereToGo: "Lender's grievance officer, then RBI Banking Ombudsman (cms.rbi.org.in); police for threats; 1930 for unlicensed loan-app fraud.",
      documentsToCarry: ['Call/message records', 'Loan agreement', 'Complaint correspondence'],
      emergency: false,
    },
    {
      id: 'cheque_bounced', title: 'A cheque given to me has bounced', category: 'MONEY_SHOPPING',
      tags: ['cheque bounce', 'cheque dishonour', 'payment bounced'],
      simpleExplanation: 'A bounced cheque is a crime in India, but you must send a demand notice fast — the deadlines are strict.',
      summary: 'Cheque dishonour is a specific criminal offence under the Negotiable Instruments Act with strict, short timelines — act quickly.',
      steps: [
        'You must issue a legal notice to the cheque issuer within 30 days of receiving the bank\'s dishonour memo, demanding payment (Section 138, Negotiable Instruments Act, 1881).',
        'The issuer then has 15 days from receiving your notice to pay.',
        "If they don't pay within that 15-day window, you can file a criminal complaint within 30 days after that window closes.",
        'Keep the original cheque, the bank\'s return memo, and proof of sending the legal notice as your core evidence.',
        "This app's Drafts tab has a Legal Notice template you can adapt — a lawyer should review the criminal complaint itself.",
      ],
      whereToGo: "Send legal notice immediately, then file a criminal complaint before the Magistrate's court with jurisdiction, within the timelines above.",
      documentsToCarry: ['Original bounced cheque', 'Bank return/dishonour memo', 'Proof of notice delivery'],
      emergency: false,
    },
    {
      id: 'cyber_fraud', title: "I've been a victim of online/cyber fraud", category: 'ONLINE_SAFETY',
      tags: ['cyber fraud', 'online scam', 'upi fraud', 'hacked account'],
      simpleExplanation: 'If someone steals your money online, call 1930 right now — the first hour matters most for getting it back.',
      summary: 'Cybercrime has a dedicated, time-sensitive national reporting system — report immediately, especially for financial fraud.',
      steps: [
        'For financial fraud, call the Cyber Crime Helpline 1930 immediately — banks can sometimes freeze/reverse a fraudulent transaction if reported within a golden window (often the first few hours).',
        'File a detailed complaint at cybercrime.gov.in with transaction IDs, screenshots, and timestamps.',
        'Also inform your bank in writing to block further transactions and request a freeze on the receiving account if possible.',
        'Keep all screenshots, SMS/email alerts, and transaction reference numbers — do not delete anything.',
        "You can also file an FIR at your local police station's cybercrime cell for serious cases.",
      ],
      whereToGo: 'Cyber Crime Helpline 1930, cybercrime.gov.in, and your bank\'s fraud reporting line.',
      documentsToCarry: ['Transaction screenshots', 'Bank statements', 'Any communication with the fraudster'],
      emergency: true,
      officialUrl: 'https://cybercrime.gov.in/',
    },
    {
      id: 'domestic_violence', title: "I'm facing domestic violence or family abuse", category: 'FAMILY_SAFETY',
      tags: ['domestic violence', 'abuse at home', 'family abuse', 'women safety'],
      simpleExplanation: "You don't have to stay in danger. Call 181 or 112 immediately — there is a specific law that protects you, with fast protection orders.",
      summary: 'The Protection of Women from Domestic Violence Act, 2005 gives fast, practical remedies — protection orders, residence rights, and monetary relief.',
      steps: [
        'If you\'re in immediate danger, call 112 (police) or 181 (Women\'s Helpline) right now.',
        'You can approach a Protection Officer (appointed in every district) or file directly before a Magistrate under the Domestic Violence Act, 2005.',
        'The law covers physical, emotional, verbal, sexual, and economic abuse, and applies to women in a domestic/family relationship, not just marriage.',
        'You can get a Protection Order (stops further abuse), a Residence Order (right to stay in the shared household), and monetary relief — often quickly.',
        'Document incidents when it\'s safe to do so: photos of injuries, messages, medical records, witness details.',
        "Free legal aid is available — call NALSA at 15100 if you can't afford a lawyer.",
      ],
      whereToGo: 'Call 112 or 181 for immediate danger. District Protection Officer or Magistrate\'s Court for legal remedies. NALSA 15100 for free legal aid.',
      documentsToCarry: ['Any medical records', 'Photos/messages if safely collected', 'ID proof'],
      emergency: true,
    },
    {
      id: 'harassment_threats', title: 'Someone is harassing or threatening me', category: 'FAMILY_SAFETY',
      tags: ['harassment', 'threats', 'stalking', 'intimidation'],
      simpleExplanation: "Threats and harassment are crimes, even if no one has been physically hurt yet — you can report it to police.",
      summary: 'Criminal intimidation, stalking, and harassment are cognizable offences under the Bharatiya Nyaya Sanhita, 2023.',
      steps: [
        'If you\'re in immediate danger, call 112.',
        'Save all evidence: messages, call logs, screenshots, voice notes — do not delete anything, even if upsetting.',
        'File a written police complaint describing the incidents with dates; for a cognizable offence, police must register an FIR.',
        "For stalking or harassment specifically targeting women, mention this explicitly — it's a distinct offence with its own provisions.",
        'You can also request a restraining/protection order through the court if the threats continue.',
      ],
      whereToGo: "Local police station (call 112 for immediate danger); Women's Helpline 181 if applicable.",
      documentsToCarry: ['Screenshots/messages/call logs', 'Written timeline of incidents'],
      emergency: true,
    },
    {
      id: 'builder_delay', title: 'My builder is delaying my flat/property possession', category: 'HOME_RENT',
      tags: ['builder delay', 'property possession delay', 'rera complaint', 'flat delay'],
      simpleExplanation: 'If your builder promised a date and missed it, you can complain to RERA — a special authority just for real estate problems.',
      summary: 'The Real Estate (Regulation and Development) Act, 2016 (RERA) gives buyers a dedicated, faster complaint route against builders.',
      steps: [
        'Check your Agreement for Sale for the promised possession date.',
        'Send a written notice to the builder demanding possession or compensation for delay.',
        "If unresolved, file a complaint with your state's RERA (Real Estate Regulatory Authority) — most states have an online portal for this.",
        'RERA can order the builder to pay interest for the delay period, or in some cases refund with interest.',
        'Keep your booking receipt, Agreement for Sale, payment records, and all communication with the builder.',
      ],
      whereToGo: "State RERA authority (search '[your state] RERA' for the official portal).",
      documentsToCarry: ['Agreement for Sale', 'Payment receipts', 'Builder communication'],
      emergency: false,
      officialUrl: 'https://rera.gov.in/',
    },
    {
      id: 'hospital_negligence', title: 'I suspect medical/hospital negligence', category: 'MONEY_SHOPPING',
      tags: ['medical negligence', 'hospital negligence', 'doctor negligence', 'wrong treatment'],
      simpleExplanation: 'If a hospital or doctor was careless and it hurt you, you can complain — but this needs medical evidence, so start collecting records now.',
      summary: 'Medical negligence claims are fact-heavy and require expert medical opinion — start by securing your records immediately.',
      steps: [
        'Request certified copies of your complete medical records from the hospital in writing — you have a right to these.',
        'Consult another doctor for a second/independent medical opinion on what happened.',
        'You can file a complaint with the State Medical Council (against the doctor) and/or a consumer complaint (treatment as a paid service) before the Consumer Commission.',
        'For serious harm, a criminal complaint may also be an option, but courts require clear proof of negligence, not just a bad outcome — consult a lawyer experienced in medical cases.',
        "Time limits apply (2 years for consumer complaints from when you knew of the negligence) — don't delay collecting records.",
      ],
      whereToGo: 'State Medical Council (professional complaint); Consumer Commission for compensation; a lawyer for a criminal complaint.',
      documentsToCarry: ['Complete medical records/discharge summary', 'Bills', 'Second opinion, if obtained'],
      emergency: false,
    },
    {
      id: 'school_college_fee_certificate', title: "School/college won't release my certificates or is overcharging fees", category: 'DOCUMENTS_ADMIN',
      tags: ['certificate withheld', 'school fee issue', 'college not releasing marksheet', 'transfer certificate'],
      simpleExplanation: 'A school or college generally cannot hold back your certificates just because of a fee dispute — most states have rules against this.',
      summary: 'Many states have specific regulations preventing institutions from withholding original certificates over fee disputes.',
      steps: [
        'Send a written request for your certificates/documents, referencing that withholding original certificates over a fee dispute is restricted in most states.',
        "Check your state's Right to Education Act rules (for schools) or the relevant university/UGC regulations (for colleges) on document withholding.",
        'If refused, complain to the District Education Officer (schools) or the university/UGC grievance cell (colleges).',
        'For fee disputes specifically, many states have Fee Regulatory Committees you can approach.',
        'Keep all fee receipts and written correspondence with the institution.',
      ],
      whereToGo: 'District Education Officer (schools); University Grievance Cell / UGC (colleges); state Fee Regulatory Committee for fee disputes.',
      documentsToCarry: ['Fee receipts', 'Admission/enrollment documents', 'Written correspondence'],
      emergency: false,
    },
    {
      id: 'lost_documents', title: "I've lost my important documents (Aadhaar, PAN, etc.)", category: 'DOCUMENTS_ADMIN',
      tags: ['lost documents', 'lost aadhaar', 'lost pan card', 'lost passport'],
      simpleExplanation: 'Losing ID documents is stressful but very fixable — file a police report if needed, then re-apply for each document.',
      summary: 'Each document has its own re-issue process; a police complaint (FIR/lost report) is often useful evidence for reissue and for preventing misuse.',
      steps: [
        'File a lost-property report at the nearest police station or online (many states offer e-FIR/lost-report portals) — useful for reissue and fraud protection.',
        "Aadhaar: retrieve/reprint via UIDAI's website (uidai.gov.in) using your enrollment ID or mobile-linked OTP.",
        'PAN: apply for a reprint/duplicate via the NSDL/UTIITSL portals.',
        'Passport: report loss to local police and the Passport Seva Kendra; a Loss/Damage report is required.',
        "Driving licence: apply for a duplicate via your state's transport department (Parivahan portal).",
        'Consider freezing/monitoring bank accounts if financial documents were also lost, to guard against misuse.',
      ],
      whereToGo: 'Local police station for a lost-property report; then the specific document\'s official portal (UIDAI, NSDL/UTIITSL, Passport Seva, Parivahan).',
      documentsToCarry: ['Any remaining ID proof', 'Photocopies of lost documents, if you have any'],
      emergency: false,
    },
    {
      id: 'rti_filing', title: 'I want to ask the government for information (RTI)', category: 'DOCUMENTS_ADMIN',
      tags: ['rti', 'right to information', 'government information request'],
      simpleExplanation: 'You can formally ask any government office a question and they must answer within 30 days — this is called an RTI.',
      summary: 'The Right to Information Act, 2005 lets any citizen request information from a public authority, with a mandatory 30-day response window.',
      steps: [
        'Identify the exact public authority that holds the information you want.',
        "Write a specific, point-wise application addressed to the Public Information Officer (PIO) of that authority — this app's Drafts tab has an RTI Application template.",
        'Pay the prescribed fee (usually ₹10, via postal order/online as per that authority\'s process).',
        'The authority must respond within 30 days (48 hours for information concerning life or liberty).',
        'If denied or ignored, you can file a First Appeal with the authority\'s Appellate Authority, then a Second Appeal with the State/Central Information Commission.',
      ],
      whereToGo: 'The Public Information Officer (PIO) of the relevant department; escalate to the Information Commission if needed.',
      documentsToCarry: ['Filled RTI application', 'Fee payment proof'],
      officialUrl: 'https://rtionline.gov.in/',
      emergency: false,
    },
    {
      id: 'free_legal_aid', title: "I can't afford a lawyer — can I get free help?", category: 'DOCUMENTS_ADMIN',
      tags: ['free legal aid', 'cannot afford lawyer', 'nalsa', 'legal aid eligibility'],
      simpleExplanation: "If you can't afford a lawyer, the government gives you one for free — just call 15100.",
      summary: 'NALSA (National Legal Services Authority) provides free legal aid to eligible categories, including women, children, SC/ST, and low-income individuals.',
      steps: [
        'Call the NALSA helpline 15100, or visit your nearest District Legal Services Authority (DLSA).',
        'Free legal aid is generally available to: women, children, SC/ST persons, industrial workmen, disaster/violence victims, persons with disabilities, and those with annual income below the state-specified limit.',
        "You'll typically need basic ID proof and a brief description of your legal issue.",
        'DLSA can provide a lawyer, help with drafting, and represent you in court proceedings, often at no cost.',
        'Law school legal aid clinics in your city may also offer free consultations.',
      ],
      whereToGo: "NALSA helpline 15100, or your District Legal Services Authority (DLSA) — search 'DLSA [your district]' for local contact.",
      documentsToCarry: ['Any ID proof', 'Income proof, if applicable', 'Brief written description of your issue'],
      emergency: false,
      officialUrl: 'https://nalsa.gov.in/',
    },
    {
      id: 'new_passport', title: 'How to apply for a new passport', category: 'DOCUMENTS_ADMIN',
      tags: ['passport application', 'new passport', 'passport seva'],
      simpleExplanation: 'Apply online at passportindia.gov.in, book a slot at your nearest Passport Seva Kendra, and bring your documents.',
      summary: 'Passport issuance is handled entirely through the Passport Seva online portal and centres.',
      steps: [
        'Register and fill the application at passportindia.gov.in.',
        'Pay the fee online — check the current fee schedule on the portal, as it varies by passport type (normal/tatkal) and booklet size.',
        'Book an appointment at your nearest Passport Seva Kendra (PSK) or Post Office PSK.',
        'Carry originals + self-attested photocopies of proof of address, proof of date of birth, and identity.',
        'Police verification is usually required (often post-issuance) — cooperate promptly to avoid delays.',
        'Track your application status online using your file number.',
      ],
      whereToGo: 'passportindia.gov.in — official Passport Seva portal.',
      documentsToCarry: ['Proof of address', 'Proof of date of birth', 'Identity proof', 'Old passport, if renewing'],
      emergency: false,
      officialUrl: 'https://www.passportindia.gov.in/',
    },
    {
      id: 'new_pan_card', title: 'How to apply for a new PAN card', category: 'DOCUMENTS_ADMIN',
      tags: ['pan card apply', 'new pan', 'pan application'],
      simpleExplanation: "Apply online through NSDL/UTIITSL with your ID, address proof, and a photo — it's usually delivered by post.",
      summary: 'PAN (Permanent Account Number) is issued by the Income Tax Department via NSDL/Protean or UTIITSL portals.',
      steps: [
        'Apply online via the Protean (formerly NSDL) or UTIITSL portal, or via the Income Tax Department\'s e-filing site.',
        'Upload/submit proof of identity, address, and date of birth, plus a passport-size photo.',
        'Pay the applicable fee online — check the current amount on the portal (differs for physical vs e-PAN, and Indian vs foreign address).',
        "You'll get an acknowledgment number to track status.",
        'The PAN card is delivered by post; an e-PAN (PDF) is usually issued faster to your registered email.',
      ],
      whereToGo: 'Protean (NSDL) or UTIITSL portal, or incometax.gov.in.',
      documentsToCarry: ['Identity proof', 'Address proof', 'Date of birth proof', 'Photograph'],
      emergency: false,
      officialUrl: 'https://www.incometax.gov.in/',
    },
    {
      id: 'aadhaar_enrollment_update', title: 'Aadhaar enrollment or correction', category: 'DOCUMENTS_ADMIN',
      tags: ['aadhaar update', 'aadhaar correction', 'new aadhaar', 'aadhaar enrollment'],
      simpleExplanation: 'Aadhaar updates (address, name, mobile) can often be done online at uidai.gov.in; new enrollment needs an Aadhaar Seva Kendra visit.',
      summary: 'UIDAI (Unique Identification Authority of India) manages Aadhaar issuance and updates.',
      steps: [
        'For a new Aadhaar (first-time), visit your nearest Aadhaar Seva Kendra or enrollment centre with proof of identity and address.',
        'For corrections (name, address, date of birth, mobile number), many updates can be done online via uidai.gov.in using your Aadhaar number and OTP.',
        'Some updates (biometric, photo) require an in-person visit to an Aadhaar centre.',
        'Check the current update fee on the UIDAI portal — it varies by update type.',
        "You can download/verify your Aadhaar (e-Aadhaar) anytime from the UIDAI website.",
      ],
      whereToGo: 'uidai.gov.in, or your nearest Aadhaar Seva Kendra.',
      documentsToCarry: ['Proof of identity', 'Proof of address', 'Mobile number for OTP'],
      emergency: false,
      officialUrl: 'https://uidai.gov.in/',
    },
    {
      id: 'voter_id_registration', title: 'How to register for a Voter ID / enroll to vote', category: 'DOCUMENTS_ADMIN',
      tags: ['voter id', 'voter registration', 'epic card', 'electoral roll'],
      simpleExplanation: "You can register to vote online once you turn 18 (or move to a new address) via the National Voters' Service Portal.",
      summary: 'Voter registration is managed by the Election Commission of India through the NVSP/Voter Helpline app.',
      steps: [
        'Check eligibility: Indian citizen, 18+ years old (or turning 18 in the qualifying year), ordinarily resident at the address you\'re registering at.',
        "Apply online at the National Voters' Service Portal (voters.eci.gov.in) or the Voter Helpline app using Form 6 (new registration) or Form 8 (correction/shift).",
        'Upload proof of age, address, and a photograph.',
        'A Booth Level Officer (BLO) may visit for verification.',
        'Track your application status online, and download your e-EPIC once approved.',
      ],
      whereToGo: 'voters.eci.gov.in or the Voter Helpline app.',
      documentsToCarry: ['Proof of age', 'Proof of address', 'Photograph'],
      emergency: false,
      officialUrl: 'https://voters.eci.gov.in/',
    },
    {
      id: 'driving_licence_new', title: 'How to apply for a new driving licence', category: 'VEHICLES',
      tags: ['new driving licence', 'learner licence', 'dl apply', 'driving test'],
      simpleExplanation: "First get a Learner's Licence (online test), practice for at least 30 days, then book a driving test for the permanent licence.",
      summary: 'Driving licences are issued by the state Transport Department via the Parivahan portal (sarathi.parivahan.gov.in).',
      steps: [
        "Apply for a Learner's Licence (LL) online via sarathi.parivahan.gov.in — you'll take an online test on traffic rules/signs.",
        'The LL is valid for 6 months; you must wait at least 30 days after getting it before applying for the permanent licence.',
        'Book a slot for the driving test (practical) at your RTO, also via the portal.',
        "Pass the test to get your permanent Driving Licence; it's typically delivered by post or downloadable as a digital DL (DigiLocker/mParivahan).",
        'Check current fees on the Parivahan portal — they vary by vehicle class and state.',
      ],
      whereToGo: 'sarathi.parivahan.gov.in, or your nearest RTO.',
      documentsToCarry: ['Proof of age (18+ for most vehicle classes)', 'Proof of address', "Learner's Licence"],
      emergency: false,
      officialUrl: 'https://sarathi.parivahan.gov.in/',
    },
    {
      id: 'driving_licence_renew_duplicate', title: 'Renew or get a duplicate driving licence', category: 'VEHICLES',
      tags: ['renew dl', 'duplicate dl', 'expired licence', 'lost driving licence'],
      simpleExplanation: 'Both renewal and duplicate DL applications can be started online at the Parivahan portal.',
      summary: 'DLs can be renewed within a window before/after expiry, and duplicates issued if lost or damaged.',
      steps: [
        'For renewal: apply via sarathi.parivahan.gov.in before your DL expires (or within the grace window your state allows — check current rules, as late renewal may need a fresh test).',
        'For a lost/damaged DL: file a police lost-report if lost, then apply for a duplicate online with your DL number.',
        'A medical certificate may be required for renewal past a certain age.',
        'Fees vary by state and reason — check the current amount on the portal.',
        'Processing is usually done at your RTO; track status online.',
      ],
      whereToGo: 'sarathi.parivahan.gov.in, or your nearest RTO.',
      documentsToCarry: ['Existing/expired DL details', 'Address proof', 'Medical certificate, if required by age', 'Police lost-report, if applicable'],
      emergency: false,
      officialUrl: 'https://sarathi.parivahan.gov.in/',
    },
    {
      id: 'rc_transfer', title: 'Transferring vehicle ownership (RC transfer)', category: 'VEHICLES',
      tags: ['rc transfer', 'vehicle ownership transfer', 'used vehicle registration'],
      simpleExplanation: 'When you buy or sell a used vehicle, the RC (registration) must be legally transferred within a set time limit.',
      summary: 'Registration Certificate transfer is a mandatory step for both buyer and seller of a used vehicle, done via the Parivahan portal/RTO.',
      steps: [
        'Both buyer and seller fill Form 29 (notice of transfer) and Form 30 (application for transfer).',
        'Submit via parivahan.gov.in or in person at the RTO, along with the sale/purchase proof, insurance, and PUC.',
        'Complete this within the timeframe your state prescribes after the sale — delays can cause complications with challans/liability.',
        'Pay the applicable transfer fee — check the current amount on the portal.',
        "Also update the vehicle insurance to the new owner's name separately with the insurer.",
      ],
      whereToGo: 'parivahan.gov.in, or your nearest RTO.',
      documentsToCarry: ['Original RC', 'Sale/purchase proof', 'Insurance', 'PUC certificate', 'ID/address proof of buyer and seller'],
      emergency: false,
      officialUrl: 'https://parivahan.gov.in/',
    },
    {
      id: 'vehicle_accident_insurance_claim', title: 'My vehicle was in an accident — insurance claim', category: 'VEHICLES',
      tags: ['accident insurance claim', 'vehicle damage claim', 'motor insurance'],
      simpleExplanation: 'Inform your insurer immediately, file a police FIR if there\'s injury/major damage, and keep all photos and repair estimates.',
      summary: 'Motor insurance claims have specific reporting timelines — delay can risk claim rejection.',
      steps: [
        'Inform your insurance company immediately (most have a 24-48 hour intimation window) — call their claims helpline or use their app.',
        'For accidents involving injury, death, or significant third-party damage, file a police FIR — this is often legally required and needed for claims.',
        'Take photos/videos of the damage and the scene before the vehicle is moved, if safe to do so.',
        'Get a repair estimate from an authorised garage (network garage for cashless claims).',
        'Submit the claim form with the FIR copy (if applicable), driving licence, RC, and insurance policy copy.',
        'For third-party injury/death claims, these are handled by the Motor Accident Claims Tribunal (MACT), separate from your own insurance claim.',
      ],
      whereToGo: "Your insurer's claims helpline/app; police station for FIR; MACT for third-party injury/death claims.",
      documentsToCarry: ['Driving licence', 'RC', 'Insurance policy', 'FIR copy, if applicable', 'Photos of damage'],
      emergency: false,
    },
    {
      id: 'vehicle_theft', title: 'My vehicle has been stolen', category: 'VEHICLES',
      tags: ['vehicle theft', 'bike stolen', 'car stolen'],
      simpleExplanation: 'File a police FIR immediately, then inform your insurer — both need to happen fast.',
      summary: 'Vehicle theft requires an FIR (mandatory for insurance claims) and prompt insurer notification.',
      steps: [
        'File an FIR at the nearest police station immediately — this is a cognizable offence and mandatory for any insurance claim.',
        'Inform your insurance company within their intimation window (often 24-48 hours) with the FIR details.',
        'Inform the RTO about the theft so the registration can be flagged.',
        "If recovered later, you'll need a 'non-traceable' report or recovery report from police depending on the case status.",
        'Keep your RC, insurance policy, and any loan/hypothecation documents ready for the claim.',
      ],
      whereToGo: 'Nearest police station for FIR; your insurer\'s claims line; RTO to flag the registration.',
      documentsToCarry: ['RC copy', 'Insurance policy', 'Keys (if available)', 'Loan/hypothecation papers, if any'],
      emergency: true,
    },
    {
      id: 'traffic_challan_dispute', title: 'I think my traffic challan/fine is wrong', category: 'VEHICLES',
      tags: ['wrong challan', 'dispute challan', 'e-challan', 'traffic fine wrong'],
      simpleExplanation: "You can check and contest an e-challan online — you don't have to just pay a fine you think is incorrect.",
      summary: "E-challans can be checked, and disputed via the traffic police's grievance process if genuinely wrong.",
      steps: [
        'Check your challan details at echallan.parivahan.gov.in using your vehicle number or challan number.',
        'If the challan seems wrong (wrong vehicle, duplicate, factually incorrect), most states have an online grievance/dispute form on the state traffic police website.',
        'Keep evidence: photos, GPS/location data, dashcam footage if available, showing why the challan is incorrect.',
        "For contested challans that go to virtual/traffic court, you may need to appear or respond within the given timeframe — don't ignore the notice.",
        'If you paid a wrongly-issued challan, refund requests are also handled through the same grievance channel.',
      ],
      whereToGo: "echallan.parivahan.gov.in and your state traffic police's online grievance portal.",
      documentsToCarry: ['Challan details/number', 'Any evidence disputing the fine'],
      emergency: false,
      officialUrl: 'https://echallan.parivahan.gov.in/',
    },
    {
      id: 'fastag_puc_issues', title: 'FASTag or PUC certificate issues', category: 'VEHICLES',
      tags: ['fastag issue', 'fastag recharge', 'puc certificate', 'pollution certificate'],
      simpleExplanation: "FASTag problems (wrong deduction, blacklist) go to your FASTag issuer bank; PUC is a quick test at any authorised pollution-check centre.",
      summary: 'FASTag is bank-issued and governed by NHAI/NPCI rules; PUC certificates are issued by authorised centres and mandatory to carry.',
      steps: [
        'For wrong FASTag deductions: raise a complaint with your issuing bank first (via app/customer care); escalate to the NHAI FASTag customer care if unresolved.',
        "If your FASTag is blacklisted/low balance, recharge via your bank's app/UPI — check your bank's specific process.",
        'For PUC: get your vehicle tested at any authorised Pollution Under Control testing centre — no appointment usually needed.',
        'Driving without a valid PUC is a finable offence — keep it current and carry proof (physical or digital).',
      ],
      whereToGo: "Your FASTag-issuing bank's app/customer care; any authorised PUC testing centre for pollution certificates.",
      documentsToCarry: ['RC (for PUC test)', 'FASTag account details'],
      emergency: false,
    },
    {
      id: 'buying_property', title: 'I want to buy a property — what should I check?', category: 'HOME_RENT',
      tags: ['buying property', 'buy a house', 'buy flat', 'property purchase checklist'],
      simpleExplanation: "Before paying anything, verify the seller's title and get an Encumbrance Certificate — this protects you from buying a disputed or mortgaged property.",
      summary: 'Property purchase requires title verification, due diligence on encumbrances/dues, and registration — mistakes here are expensive and hard to reverse.',
      steps: [
        "Verify the seller's title documents (original sale deed chain) — consult a property lawyer to check clear, marketable title.",
        "Get an Encumbrance Certificate (EC) from the Sub-Registrar's office to confirm the property has no pending loans/legal disputes.",
        'Check property tax receipts are up to date and there are no dues.',
        "For under-construction property, verify RERA registration of the project on your state's RERA portal.",
        "Execute the Sale Deed and register it at the Sub-Registrar's office — registration is mandatory for the transfer to be legally valid.",
        'After registration, apply for mutation (updating revenue/municipal records to your name) — this is separate from registration and easy to forget.',
        'Stamp duty and registration fees apply and vary by state — check your state\'s current rates before budgeting; do not pay in unaccounted cash.',
      ],
      whereToGo: "Sub-Registrar's office for EC and registration; state RERA portal for under-construction projects; a property lawyer for title verification.",
      documentsToCarry: ['Sale deed chain / title documents', 'Encumbrance Certificate', 'Property tax receipts', 'Aadhaar, PAN'],
      emergency: false,
      officialUrl: 'https://rera.gov.in/',
    },
    {
      id: 'selling_property', title: 'I want to sell my property', category: 'HOME_RENT',
      tags: ['selling property', 'sell house', 'sell flat'],
      simpleExplanation: 'Get your documents in order (title, tax receipts, EC), agree terms in writing, then execute and register the sale deed.',
      summary: 'Selling requires the same document readiness as buying, plus tax considerations (capital gains) on your side.',
      steps: [
        'Gather your title documents, latest property tax receipts, and an Encumbrance Certificate to show a clean title to buyers.',
        "If there's an existing home loan, get a No Objection Certificate (NOC) / loan closure from your bank before or as part of the sale.",
        'Sign an Agreement to Sell with the buyer specifying price, payment schedule, and possession date.',
        "Execute and register the Sale Deed at the Sub-Registrar's office.",
        'Consult a CA about capital gains tax implications and available exemptions (e.g., reinvestment) — this affects your tax filing.',
      ],
      whereToGo: "Sub-Registrar's office for registration; your bank for loan NOC/closure, if applicable; a CA for tax implications.",
      documentsToCarry: ['Title documents', 'Property tax receipts', 'Encumbrance Certificate', 'Loan NOC, if applicable'],
      emergency: false,
    },
    {
      id: 'gift_deed_property', title: 'I want to gift a property to a family member', category: 'HOME_RENT',
      tags: ['gift deed', 'gifting property', 'transfer property to family'],
      simpleExplanation: "A gift of property must be done through a registered Gift Deed — a verbal or informal gift isn't legally valid for immovable property.",
      summary: 'Gift Deeds transfer ownership without consideration but still require registration and (in most states) attract stamp duty.',
      steps: [
        'Draft a Gift Deed specifying the donor, donee, property details, and that it\'s a gift without consideration.',
        "Many states offer reduced stamp duty for gifts between specified close relatives — check your state's current rules.",
        "Register the Gift Deed at the Sub-Registrar's office — registration is mandatory for it to be legally effective.",
        "Apply for mutation afterward to update revenue records in the donee's name.",
        'Once registered and accepted, a gift is generally irrevocable except in specific legally recognised circumstances — take this seriously before signing.',
      ],
      whereToGo: "Sub-Registrar's office for registration; a property lawyer to draft the deed correctly.",
      documentsToCarry: ['Property title documents', 'ID proof of donor and donee', 'Property tax receipts'],
      emergency: false,
    },
    {
      id: 'property_partition', title: 'Dividing inherited/joint property among family members', category: 'HOME_RENT',
      tags: ['property partition', 'dividing inherited property', 'joint property dispute'],
      simpleExplanation: 'Family members can divide jointly-owned/inherited property either by mutual agreement (Partition Deed) or, if they disagree, through a court partition suit.',
      summary: 'Partition can be amicable (registered Partition Deed) or contested (civil suit) — the right path depends on whether all co-owners agree.',
      steps: [
        "If all co-owners agree on the division, draft and register a Partition Deed at the Sub-Registrar's office specifying each person's share.",
        'If co-owners disagree, any co-owner can file a partition suit in the civil court having jurisdiction over the property.',
        'Gather proof of ownership/inheritance (will, succession certificate, or legal heir certificate) before proceeding either way.',
        'Mutation must be updated after any partition to reflect the new ownership shares in revenue records.',
        'Consult a property/family lawyer — partition disputes are fact-heavy and mistakes are hard to undo.',
      ],
      whereToGo: "Sub-Registrar's office for an amicable Partition Deed; Civil Court for a contested partition suit.",
      documentsToCarry: ['Title/inheritance documents', 'Will or succession/legal heir certificate, if applicable', 'ID proof of all co-owners'],
      emergency: false,
    },
    {
      id: 'property_mutation', title: 'Property mutation — updating ownership records', category: 'HOME_RENT',
      tags: ['mutation', 'property records update', 'dakhil kharij'],
      simpleExplanation: 'After buying, inheriting, or being gifted property, you must separately update the government\'s revenue/municipal records to your name — this is mutation, not the same as registration.',
      summary: 'Mutation (also called Dakhil Kharij in some states) updates land revenue records for tax and administrative purposes.',
      steps: [
        "Apply for mutation at your local municipal corporation/panchayat or revenue office (often online via your state's land records portal).",
        'Submit the registered sale deed / gift deed / succession certificate along with the application.',
        "Property tax records get updated to the new owner's name once mutation is approved.",
        "This is required even though the sale deed registration already legally transferred ownership — mutation is for administrative/tax records, not for legal title.",
        "Don't skip this step — it can cause problems paying property tax or reselling later.",
      ],
      whereToGo: "Local municipal corporation/panchayat, or your state's online land records portal.",
      documentsToCarry: ['Registered sale/gift deed', 'Previous property tax receipt', 'ID proof'],
      emergency: false,
    },
    {
      id: 'society_rwa_issues', title: 'Dispute with my housing society / RWA', category: 'HOME_RENT',
      tags: ['society dispute', 'rwa complaint', 'maintenance dispute', 'cooperative society'],
      simpleExplanation: "Housing societies are governed by their own bye-laws and state Cooperative Societies Act — disputes have a specific escalation path, not just informal complaints.",
      summary: 'Most housing society disputes (maintenance, common area misuse, arbitrary rules) are handled under state Cooperative Societies laws.',
      steps: [
        "Raise the issue in writing with the society's Managing Committee first, referencing the specific bye-law.",
        'If unresolved, most states allow a complaint to the Registrar of Cooperative Societies.',
        'For disputes between members and the society, the Cooperative Court / Tribunal (where it exists in your state) can adjudicate.',
        'Keep records: society bye-laws, maintenance bills, minutes of meetings, and written correspondence.',
        'For consumer-service-type complaints (e.g. society failing to provide agreed amenities), a consumer complaint may also be an option.',
      ],
      whereToGo: 'Society Managing Committee first; then Registrar of Cooperative Societies for your state.',
      documentsToCarry: ['Society bye-laws', 'Maintenance bills/receipts', 'Written correspondence'],
      emergency: false,
    },
    {
      id: 'pf_withdrawal', title: 'How to withdraw my PF (Provident Fund)', category: 'WORK',
      tags: ['pf withdrawal', 'epf withdrawal', 'provident fund claim'],
      simpleExplanation: 'You can withdraw your PF online through the EPFO portal using your UAN, once eligible.',
      summary: "EPFO (Employees' Provident Fund Organisation) allows online withdrawal/claims through the member portal.",
      steps: [
        'Activate your UAN (Universal Account Number) on the EPFO member portal if not already done, and link Aadhaar/bank details.',
        'Ensure your Aadhaar, PAN, and bank account are seeded and verified on the UAN portal.',
        'File your claim online (Form 19 for final settlement, Form 31 for partial withdrawal, Form 10C for pension withdrawal) via the EPFO portal.',
        'Full withdrawal is typically allowed after 2 months of unemployment; partial withdrawal has its own eligibility rules (medical, housing, education, etc.).',
        'Track claim status online; funds are usually credited directly to your linked bank account.',
      ],
      whereToGo: 'EPFO member portal (epfindia.gov.in / unifiedportal-mem.epfindia.gov.in).',
      documentsToCarry: ['UAN', 'Aadhaar', 'PAN', 'Bank account details (linked to UAN)'],
      emergency: false,
      officialUrl: 'https://unifiedportal-mem.epfindia.gov.in/',
    },
    {
      id: 'esic_benefits', title: 'ESIC — using my medical/insurance benefits', category: 'WORK',
      tags: ['esic', 'esi benefits', 'employee state insurance'],
      simpleExplanation: "If your salary is under the ESIC wage limit, you're entitled to free/subsidised medical treatment and cash benefits during illness — check your ESIC card.",
      summary: "The Employees' State Insurance Corporation (ESIC) provides medical and cash benefits to eligible employees.",
      steps: [
        'Check if you\'re covered — ESIC applies to employees earning under the wage ceiling notified by ESIC (check the current limit on esic.gov.in).',
        'Get treatment at an ESIC dispensary/hospital using your ESIC insurance number/e-Pehchan card.',
        'For sickness/maternity/disablement cash benefits, claims are filed through your employer or directly on the ESIC portal.',
        "If your employer isn't remitting your ESIC contributions despite deducting them, this is a separate serious issue — you can complain to the ESIC regional office.",
        'Dependents can also claim benefits under certain circumstances — check eligibility on the portal.',
      ],
      whereToGo: 'esic.gov.in, or your nearest ESIC branch office/dispensary.',
      documentsToCarry: ['ESIC insurance number / e-Pehchan card', 'ID proof'],
      emergency: false,
      officialUrl: 'https://www.esic.gov.in/',
    },
    {
      id: 'gratuity_claim', title: 'Claiming my gratuity after leaving a job', category: 'WORK',
      tags: ['gratuity', 'gratuity claim', 'gratuity not paid'],
      simpleExplanation: "If you've worked 5+ years at an employer, you're generally entitled to gratuity when you leave — your employer must pay it within a set time.",
      summary: 'Gratuity is governed by the Payment of Gratuity Act, 1972, for employees who\'ve completed continuous service (usually 5 years, with some exceptions).',
      steps: [
        'Submit Form I to your employer within 30 days of becoming eligible (leaving/retiring) to formally claim gratuity.',
        'The employer must determine and pay the gratuity amount within 30 days of it becoming due.',
        'If unpaid or disputed, you can approach the Controlling Authority under the Payment of Gratuity Act (usually the Labour Commissioner\'s office) with Form N.',
        'Keep your appointment letter, relieving letter, and salary records as proof of tenure and last drawn salary.',
        'The 5-year continuous service requirement has exceptions (e.g., death, disablement) — check if these apply to your case.',
      ],
      whereToGo: 'Your employer first (Form I); then the Controlling Authority under the Payment of Gratuity Act (Labour Commissioner\'s office) if unpaid.',
      documentsToCarry: ['Appointment letter', 'Relieving/experience letter', 'Salary slips'],
      emergency: false,
    },
    {
      id: 'maternity_benefit', title: 'My employer is denying maternity leave/benefits', category: 'WORK',
      tags: ['maternity leave', 'maternity benefit denied', 'pregnancy at work'],
      simpleExplanation: "Eligible women employees are legally entitled to paid maternity leave — an employer denying this is breaking the law, not just being unfair.",
      summary: 'The Maternity Benefit Act, 1961 (as amended) guarantees paid leave and protections for eligible women employees.',
      steps: [
        'Check eligibility — generally applies if you\'ve worked at least 80 days in the 12 months before your expected delivery date.',
        'Give your employer written notice of your pregnancy and expected leave dates in the prescribed form.',
        "You're entitled to paid leave (currently up to 26 weeks for the first two children, per the amended Act — verify current provisions), plus protection from dismissal during this period.",
        'If denied, first raise it in writing with HR/management, referencing the Maternity Benefit Act.',
        'If unresolved, complain to the Labour Commissioner\'s office / Inspector under the Act — this can also be a criminal offence for the employer in serious violations.',
      ],
      whereToGo: "Labour Commissioner's office if your employer denies statutory maternity benefits after a written request.",
      documentsToCarry: ['Appointment letter', 'Written notice given to employer', 'Medical certificate confirming pregnancy/delivery date'],
      emergency: false,
    },
    {
      id: 'resignation_notice_period', title: 'Resignation and notice period disputes', category: 'WORK',
      tags: ['resignation', 'notice period dispute', 'employer forcing to stay'],
      simpleExplanation: 'Your notice period is whatever your appointment letter says — an employer generally cannot force you to stay beyond it, though they can seek notice-pay if you leave early.',
      summary: 'Notice period obligations are contractual, defined in your appointment letter, not a blanket legal rule.',
      steps: [
        'Check your appointment letter/contract for the exact notice period and any buyout clause (paying in lieu of notice).',
        'Submit your resignation in writing, keeping a dated copy/acknowledgment.',
        'If the employer refuses to relieve you or withholds your full & final settlement/experience letter without valid contractual basis, send a written follow-up.',
        'If unresolved, you can approach the Labour Commissioner\'s office, especially if dues (salary, gratuity) are being withheld.',
        'Non-compete or garden leave clauses, if any, should be reviewed carefully — enforceability varies.',
      ],
      whereToGo: "Labour Commissioner's office if your employer withholds dues or documents after a valid resignation.",
      documentsToCarry: ['Appointment letter/contract', 'Resignation letter with acknowledgment', 'Salary records'],
      emergency: false,
    },
    {
      id: 'experience_letter_denied', title: 'Employer refuses to give my experience/relieving letter', category: 'WORK',
      tags: ['experience letter denied', 'relieving letter refused', 'employer not giving documents'],
      simpleExplanation: 'An experience/relieving letter is normally owed once you\'ve completed your notice period properly — a refusal without valid reason can be escalated.',
      summary: 'While not always a distinct statutory right in every state, withholding basic employment documents without valid cause is generally considered unfair and can be challenged.',
      steps: [
        'Send a written request to HR for your relieving and experience letters, referencing that you completed your notice period/settlement.',
        'If refused, check if the employer is citing a genuine dispute (e.g., pending dues, disciplinary issue) — respond to that specifically.',
        'You can escalate to the Labour Commissioner\'s office, especially if this is tied to withheld wages/dues.',
        'Keep your resignation acknowledgment, last working day confirmation, and any settlement correspondence as evidence.',
        'A bank statement showing your salary credits can serve as informal proof of employment if documents are delayed.',
      ],
      whereToGo: "Labour Commissioner's office if documents are withheld without valid reason alongside pending dues.",
      documentsToCarry: ['Resignation acknowledgment', 'Last working day confirmation', 'Salary records'],
      emergency: false,
    },
    {
      id: 'food_safety_complaint', title: 'I found something wrong with packaged/restaurant food', category: 'MONEY_SHOPPING',
      tags: ['food safety complaint', 'fssai complaint', 'contaminated food', 'expired food'],
      simpleExplanation: 'Food safety issues (contamination, expired products, mislabeling) can be reported directly to FSSAI, separate from a regular consumer complaint.',
      summary: 'The Food Safety and Standards Authority of India (FSSAI) handles food safety complaints specifically.',
      steps: [
        "Keep the product/packaging (with batch number, expiry date) and any receipt as evidence — don't discard it.",
        'File a complaint on the FSSAI Food Safety Voice of Consumers portal or their toll-free number.',
        'You can also pursue a parallel consumer complaint (refund/compensation) via the National Consumer Helpline (1915) or Consumer Commission.',
        'For serious health harm, keep medical records and consider informing the local police/health department as well.',
        'Photograph the product, packaging, and any visible contamination before consuming further or discarding.',
      ],
      whereToGo: "FSSAI's consumer complaint portal/toll-free line; National Consumer Helpline 1915 for refund/compensation.",
      documentsToCarry: ['Product/packaging with batch/expiry details', 'Purchase receipt', 'Photos', 'Medical records, if harmed'],
      emergency: false,
      officialUrl: 'https://www.fssai.gov.in/',
    },
    {
      id: 'insurance_claim_rejected', title: 'My insurance claim was rejected or delayed', category: 'MONEY_SHOPPING',
      tags: ['insurance claim rejected', 'insurance denied', 'insurance delay'],
      simpleExplanation: 'If your insurer wrongly rejects or delays your claim, you can complain to the insurer\'s grievance cell, then IRDAI or the Insurance Ombudsman.',
      summary: "Insurance grievances have a structured escalation path through IRDAI's Integrated Grievance Management System and the Ombudsman scheme.",
      steps: [
        "First file a written complaint with your insurer's Grievance Redressal Officer, referencing your policy and claim number.",
        "If unresolved within 30 days, escalate to IRDAI's Integrated Grievance Management System (igms.irda.gov.in) or their toll-free line.",
        "For claims within the Ombudsman's monetary jurisdiction, you can approach the Insurance Ombudsman for your region — this is a free, faster alternative to court.",
        'Keep your policy document, claim form, rejection letter (with reasons), and all correspondence.',
        "You can also file a consumer complaint before the Consumer Commission if the Ombudsman route doesn't apply or isn't satisfactory.",
      ],
      whereToGo: "Insurer's Grievance Officer, then IRDAI (igms.irda.gov.in) or the Insurance Ombudsman for your region.",
      documentsToCarry: ['Policy document', 'Claim form', 'Rejection letter with reasons', 'All correspondence with insurer'],
      emergency: false,
      officialUrl: 'https://irdai.gov.in/',
    },
    {
      id: 'travel_airline_complaint', title: 'Airline/travel company issue (delay, cancellation, denied boarding)', category: 'MONEY_SHOPPING',
      tags: ['flight delay compensation', 'flight cancelled', 'denied boarding', 'airline complaint'],
      simpleExplanation: 'Airlines have specific compensation/refund duties for cancellations, long delays, and denied boarding under DGCA rules.',
      summary: 'The Directorate General of Civil Aviation (DGCA) sets passenger rights rules that airlines must follow.',
      steps: [
        "For cancellations/long delays, check the airline's obligations under DGCA's Civil Aviation Requirements — you may be entitled to alternate flight, refund, or compensation depending on notice given.",
        "For denied boarding (overbooking), airlines must offer compensation per DGCA rules if you weren't offered an alternative you accepted.",
        "First file a complaint with the airline's customer service/grievance cell in writing.",
        'If unresolved, escalate to AirSewa (airsewa.gov.in), the government\'s air travel grievance portal.',
        'For a monetary claim, you can also file a consumer complaint before the Consumer Commission.',
      ],
      whereToGo: "Airline's grievance cell first, then airsewa.gov.in (Ministry of Civil Aviation's grievance portal).",
      documentsToCarry: ['Ticket/booking confirmation', 'Boarding pass, if available', 'Communication with airline'],
      emergency: false,
      officialUrl: 'https://airsewa.gov.in/',
    },
    {
      id: 'bank_complaint', title: 'I have a complaint against my bank', category: 'MONEY_SHOPPING',
      tags: ['bank complaint', 'banking ombudsman', 'bank service issue'],
      simpleExplanation: "Bank complaints (wrong charges, service failure, ATM issues) go first to the bank, then to the RBI Banking Ombudsman if unresolved — this is a free process.",
      summary: "The RBI's Banking Ombudsman Scheme provides a free grievance redressal mechanism against banks.",
      steps: [
        "First raise the complaint with your bank's branch/customer care and get a complaint reference number.",
        'If unresolved within 30 days, or if you\'re unsatisfied with the response, escalate to the RBI Banking Ombudsman via cms.rbi.org.in.',
        "The Ombudsman process is free and doesn't require a lawyer.",
        'Keep your account statements, transaction references, and all correspondence with the bank.',
        'For disputed/unauthorised transactions, report immediately — banks have specific liability rules that favour prompt reporting.',
      ],
      whereToGo: "Your bank's grievance cell first, then RBI Banking Ombudsman (cms.rbi.org.in).",
      documentsToCarry: ['Account statements', 'Transaction reference numbers', 'Correspondence with bank', 'Complaint reference number'],
      emergency: false,
      officialUrl: 'https://cms.rbi.org.in/',
    },
    {
      id: 'hospital_bill_dispute', title: 'Hospital is overcharging or disputing my bill', category: 'MONEY_SHOPPING',
      tags: ['hospital overcharging', 'medical bill dispute', 'hospital bill complaint'],
      simpleExplanation: "You have a right to an itemized bill and to question charges — hospitals can't refuse to explain what you're being charged for.",
      summary: 'Patients are entitled to transparent, itemized billing; disputes can be escalated as a consumer/service complaint.',
      steps: [
        "Request a detailed, itemized bill in writing — you're entitled to know what each charge is for.",
        'Compare against your insurance/TPA pre-authorization if applicable, and flag discrepancies in writing.',
        'If the hospital refuses to correct clear errors, file a complaint with the State Medical Council (for ethical/billing conduct issues) or a consumer complaint (deficiency in service).',
        "For empanelled/insured treatment, your insurer's grievance cell can also help resolve billing disputes.",
        'Keep all bills, prescriptions, and communication as evidence.',
      ],
      whereToGo: "Hospital's billing/grievance department first; State Medical Council or Consumer Commission if unresolved.",
      documentsToCarry: ['Itemized bill', 'Insurance/TPA pre-authorization, if applicable', 'Written correspondence'],
      emergency: false,
    },
    {
      id: 'company_registration', title: 'How to register a company in India', category: 'BUSINESS',
      tags: ['company registration', 'register private limited', 'incorporate company', 'mca registration'],
      simpleExplanation: 'Most small businesses register as a Private Limited Company or LLP through the MCA\'s online portal — the whole process can be done digitally.',
      summary: 'Company incorporation in India is handled online through the Ministry of Corporate Affairs (MCA) SPICe+ form.',
      steps: [
        'Decide the business structure: Private Limited Company, LLP, One Person Company, or Partnership — each has different compliance burdens.',
        'Obtain Digital Signature Certificates (DSC) for the proposed directors/partners.',
        "Reserve your company name and file incorporation via the MCA's SPICe+ (Simplified Proforma for Incorporating Company Electronically) portal, which also covers PAN, TAN, EPFO, ESIC, and GST registration in one filing.",
        'Draft the Memorandum and Articles of Association (MOA/AOA) for a company, or an LLP Agreement for an LLP.',
        'Check current government fees on the MCA portal — they vary by authorized capital and state (stamp duty).',
        'Post-incorporation, comply with ongoing filings (annual returns, financial statements) to avoid penalties.',
      ],
      whereToGo: 'mca.gov.in — Ministry of Corporate Affairs portal (SPICe+ form).',
      documentsToCarry: ['Identity/address proof of directors', 'Registered office address proof', 'DSC and DIN of directors'],
      emergency: false,
      officialUrl: 'https://www.mca.gov.in/',
    },
    {
      id: 'startup_india_registration', title: 'Registering under Startup India', category: 'BUSINESS',
      tags: ['startup india', 'dpiit recognition', 'startup registration'],
      simpleExplanation: 'Startup India recognition (DPIIT certificate) can unlock tax benefits and easier compliance — it\'s a separate registration after you\'ve already incorporated your company/LLP.',
      summary: 'DPIIT (Department for Promotion of Industry and Internal Trade) recognition under Startup India offers specific benefits to eligible young companies.',
      steps: [
        'First incorporate your entity (Private Limited, LLP, or Registered Partnership).',
        'Check eligibility: generally under 10 years old, turnover under the prescribed limit, and working towards innovation/improvement of products or scalable business models.',
        'Apply for DPIIT recognition via the Startup India portal (startupindia.gov.in) with your incorporation certificate and a brief write-up on your business.',
        'Once recognised, you can apply separately for income tax exemption (Section 80-IAC) and other benefits — these require additional applications, not automatic.',
        'Keep your recognition certificate for accessing startup-specific schemes, funds, and relaxed compliance.',
      ],
      whereToGo: 'startupindia.gov.in.',
      documentsToCarry: ['Certificate of incorporation', 'Business description/pitch', 'PAN of the entity'],
      emergency: false,
      officialUrl: 'https://www.startupindia.gov.in/',
    },
    {
      id: 'msme_udyam_registration', title: 'MSME / Udyam registration for my business', category: 'BUSINESS',
      tags: ['msme registration', 'udyam registration', 'small business registration'],
      simpleExplanation: 'Udyam registration is free, online, and takes minutes with just your Aadhaar and PAN — it unlocks MSME benefits like easier loans and delayed-payment protection.',
      summary: 'Udyam Registration is the official MSME registration process, based on investment and turnover criteria.',
      steps: [
        'Go to the Udyam Registration portal (udyamregistration.gov.in) — registration is free.',
        'Register using your Aadhaar number (proprietor/partner/director as applicable) and PAN.',
        'Provide business details, investment in plant/machinery or equipment, and turnover — this determines your classification (micro/small/medium).',
        "You'll get an Udyam Registration Certificate instantly upon successful submission.",
        'This registration helps with collateral-free loans, delayed payment protection under the MSMED Act, and various government scheme eligibility.',
      ],
      whereToGo: 'udyamregistration.gov.in.',
      documentsToCarry: ['Aadhaar', 'PAN', 'Business/bank details'],
      emergency: false,
      officialUrl: 'https://udyamregistration.gov.in/',
    },
    {
      id: 'fssai_licence', title: 'FSSAI licence for a food business', category: 'BUSINESS',
      tags: ['fssai licence', 'food business licence', 'food safety registration'],
      simpleExplanation: 'Any food business (even a home-based one) needs at least a basic FSSAI registration, and larger ones need a full licence.',
      summary: 'FSSAI registration/licensing is mandatory for anyone manufacturing, storing, distributing, or selling food, based on business size.',
      steps: [
        'Determine your category: Basic Registration (small/petty food businesses under a turnover threshold), State Licence (medium), or Central Licence (large/import-export) — thresholds are set by FSSAI, check current limits.',
        'Apply online via the FoSCoS (Food Safety Compliance System) portal.',
        'Submit business details, food category, and required documents (varies by registration type).',
        'Display your FSSAI registration/licence number on your premises and packaging/products as required.',
        'Renew before expiry — operating without a valid, current FSSAI registration is an offence.',
      ],
      whereToGo: 'foscos.fssai.gov.in.',
      documentsToCarry: ['Identity/address proof', 'Business address proof', 'Food category details'],
      emergency: false,
      officialUrl: 'https://foscos.fssai.gov.in/',
    },
    {
      id: 'shop_establishment_act', title: 'Shop & Establishment Act registration', category: 'BUSINESS',
      tags: ['shop act registration', 'gumasta licence', 'establishment registration'],
      simpleExplanation: "Most commercial establishments (shops, offices) must register under their state's Shops & Establishments Act — this is often the very first licence a small business needs.",
      summary: "Shops & Establishments registration (sometimes called 'Gumasta' in some states) is state-specific and generally mandatory before opening for business.",
      steps: [
        "Check your specific state's Shops & Establishments rules — the process and portal is state-run, not central.",
        'Apply online via your state\'s labour department portal, providing business name, address, nature of business, and employee count.',
        'Pay the applicable registration fee (varies by state and establishment size).',
        'Display the registration certificate at your premises as required.',
        "Renew as per your state's validity period — many states have moved to longer or lifetime validity, but check current rules.",
      ],
      whereToGo: "Your state's Labour Department / Shops and Establishments online portal.",
      documentsToCarry: ['Business address proof', 'Identity proof of owner', 'Details of employees, if any'],
      emergency: false,
    },
    {
      id: 'trademark_registration', title: 'Registering a trademark for my business/brand', category: 'BUSINESS',
      tags: ['trademark registration', 'trademark application', 'brand name protection'],
      simpleExplanation: 'Registering your brand name/logo as a trademark gives you exclusive legal rights to it — do a search first to make sure it\'s not already taken.',
      summary: 'Trademark registration is handled by the Controller General of Patents, Designs and Trade Marks (CGPDTM).',
      steps: [
        "Search the existing trademark database (ipindia.gov.in) to check your desired mark isn't already registered/similar to an existing one.",
        'File your application online via the IP India portal, selecting the correct class(es) of goods/services.',
        'The application is examined, published in the Trademark Journal for opposition, and if unopposed/resolved, proceeds to registration.',
        'The whole process can take many months to a few years — using ™ is allowed once applied; ® only after registration.',
        'Once registered, renew periodically (check current renewal period) to keep protection active.',
      ],
      whereToGo: 'ipindia.gov.in — Office of the Controller General of Patents, Designs and Trade Marks.',
      documentsToCarry: ['Brand name/logo details', "Business proof (if registering in a company's name)"],
      emergency: false,
      officialUrl: 'https://ipindia.gov.in/',
    },
    {
      id: 'import_export_code', title: 'Getting an Import Export Code (IEC)', category: 'BUSINESS',
      tags: ['import export code', 'iec registration', 'export import licence'],
      simpleExplanation: 'If you want to import or export goods/services commercially, you need an IEC — it\'s a one-time online registration.',
      summary: 'The Import Export Code (IEC) is issued by the Directorate General of Foreign Trade (DGFT) and is mandatory for import/export businesses.',
      steps: [
        'Apply online via the DGFT portal (dgft.gov.in) using your business PAN.',
        'Provide business details, bank account, and address proof.',
        'Pay the applicable fee — check the current amount on the DGFT portal.',
        'The IEC is typically issued digitally within a few working days.',
        'IEC now requires periodic online updation/confirmation (even with no changes) — check current DGFT rules to avoid deactivation.',
      ],
      whereToGo: 'dgft.gov.in — Directorate General of Foreign Trade.',
      documentsToCarry: ['Business PAN', 'Bank account details', 'Address proof'],
      emergency: false,
      officialUrl: 'https://www.dgft.gov.in/',
    },
  ],
}

export async function GET() {
  return NextResponse.json(DATA, {
    headers: {
      'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
    },
  })
}
