// Regenerates src/Root.tsx from the ad manifest, registering only files that
// exist on disk (so a missing/failed ad never breaks the bundle).
// Run: node scripts/gen-root.mjs
import { existsSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// [file (no ext), exported component, durationInFrames]
const ADS = [
  ['Ad01OrderPing', 'Ad01OrderPing', 300],
  ['Ad02OrderStack', 'Ad02OrderStack', 450],
  ['Ad03StoreBuild', 'Ad03StoreBuild', 450],
  ['C02_TwoYearsOfSomeday', 'C02', 450],
  ['C03_TheShutter', 'C03', 450],
  ['C04_MontageOfExcuses', 'C04', 450],
  ['C05_MothersRecipes', 'C05', 450],
  ['C06_FirstCustomerIsMom', 'C06', 450],
  ['C07_HostelRoomHQ', 'C07', 450],
  ['C08_TwoMinuteSilence', 'C08', 450],
  ['C09_RainDelivery', 'C09', 450],
  ['C10_OneYearFromNow', 'C10', 450],
  ['C11_SpeedrunRealtime', 'C11', 450],
  ['C13_PasteLinkProduct', 'C13', 450],
  ['C14_CameraTrick', 'C14', 450],
  ['C15_CODWithoutFear', 'C15', 450],
  ['C16_FunnelComesAlive', 'C16', 450],
  ['C17_AbandonedCartRescue', 'C17', 450],
  ['C18_GSTWithoutFear', 'C18', 450],
  ['C19_BioLinkUpgrade', 'C19', 450],
  ['C20_DashboardDay', 'C20', 450],
  ['C21_DollarBillProblem', 'C21', 450],
  ['C22_CommissionCalculator', 'C22', 450],
  ['C23_PluginMountain', 'C23', 450],
  ['C24_MarketplaceVsYourPlace', 'C24', 450],
  ['C25_TheSwitch', 'C25', 450],
  ['C26_LockScreenHero', 'C26', 450],
  ['C27_OneTapFulfil', 'C27', 450],
  ['C28_TheCommute', 'C28', 450],
  ['C29_VolumeOffTest', 'C29', 450],
  ['C30_NightMarketGlow', 'C30', 450],
  ['C31_NicheJewellery', 'C31', 360],
  ['C32_NicheBakery', 'C32', 360],
  ['C33_NicheThrift', 'C33', 360],
  ['C34_NicheSkincare', 'C34', 360],
  ['C35_NicheSupplements', 'C35', 360],
  ['C36_NicheSaree', 'C36', 360],
  ['C37_NichePhoneAccessories', 'C37', 360],
  ['C38_NicheCandles', 'C38', 360],
  ['C39_NicheStationery', 'C39', 360],
  ['C40_NichePetSupplies', 'C40', 360],
  ['C41_AntiGuru', 'C41', 450],
  ['C42_Seed', 'C42', 450],
  ['C43_CommentToStore', 'C43', 450],
  ['C44_ReverseUnboxing', 'C44', 450],
  ['C45_HundredStores', 'C45', 450],
  ['C46_POVFirstSale', 'C46', 450],
  ['C47_EmptyChairInterview', 'C47', 450],
  ['C48_SpeedrunChallenge', 'C48', 450],
  ['C49_TheRefund', 'C49', 450],
  ['C50_DiwaliLamp', 'C50', 450],
]

const present = ADS.filter(([file]) => existsSync(join(root, 'src', 'ads', `${file}.tsx`)))
const missing = ADS.filter(([file]) => !existsSync(join(root, 'src', 'ads', `${file}.tsx`)))

const compId = (file, comp) =>
  comp.startsWith('Ad') ? { Ad01OrderPing: 'Ad01-OrderPing', Ad02OrderStack: 'Ad02-OrderStack', Ad03StoreBuild: 'Ad03-StoreBuild' }[file]
    : file.replace('_', '-')

const src = `import React from 'react'
import { Composition } from 'remotion'
import { FPS } from './brand'
${present.map(([file, comp]) => `import { ${comp} } from './ads/${file}'`).join('\n')}

/** AUTO-GENERATED by scripts/gen-root.mjs — edit the manifest there, not here. */
export const RemotionRoot: React.FC = () => {
  return (
    <>
${present.map(([file, comp, dur]) => `      <Composition id="${compId(file, comp)}" component={${comp}} durationInFrames={${dur}} fps={FPS} width={1080} height={1920} />`).join('\n')}
    </>
  )
}
`
writeFileSync(join(root, 'src', 'Root.tsx'), src)
console.log(`registered ${present.length} compositions${missing.length ? `; MISSING: ${missing.map(([f]) => f).join(', ')}` : ''}`)
