import React from 'react'
import { Composition } from 'remotion'
import { FPS } from './brand'
import { Ad01OrderPing } from './ads/Ad01OrderPing'
import { Ad02OrderStack } from './ads/Ad02OrderStack'
import { Ad03StoreBuild } from './ads/Ad03StoreBuild'
import { C02 } from './ads/C02_TwoYearsOfSomeday'
import { C03 } from './ads/C03_TheShutter'
import { C07 } from './ads/C07_HostelRoomHQ'
import { C08 } from './ads/C08_TwoMinuteSilence'
import { C09 } from './ads/C09_RainDelivery'
import { C13 } from './ads/C13_PasteLinkProduct'
import { C18 } from './ads/C18_GSTWithoutFear'
import { C19 } from './ads/C19_BioLinkUpgrade'
import { C23 } from './ads/C23_PluginMountain'
import { C26 } from './ads/C26_LockScreenHero'
import { C27 } from './ads/C27_OneTapFulfil'
import { C31 } from './ads/C31_NicheJewellery'
import { C45 } from './ads/C45_HundredStores'
import { C47 } from './ads/C47_EmptyChairInterview'

/** AUTO-GENERATED by scripts/gen-root.mjs — edit the manifest there, not here. */
export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition id="Ad01-OrderPing" component={Ad01OrderPing} durationInFrames={300} fps={FPS} width={1080} height={1920} />
      <Composition id="Ad02-OrderStack" component={Ad02OrderStack} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="Ad03-StoreBuild" component={Ad03StoreBuild} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C02-TwoYearsOfSomeday" component={C02} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C03-TheShutter" component={C03} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C07-HostelRoomHQ" component={C07} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C08-TwoMinuteSilence" component={C08} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C09-RainDelivery" component={C09} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C13-PasteLinkProduct" component={C13} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C18-GSTWithoutFear" component={C18} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C19-BioLinkUpgrade" component={C19} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C23-PluginMountain" component={C23} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C26-LockScreenHero" component={C26} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C27-OneTapFulfil" component={C27} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C31-NicheJewellery" component={C31} durationInFrames={360} fps={FPS} width={1080} height={1920} />
      <Composition id="C45-HundredStores" component={C45} durationInFrames={450} fps={FPS} width={1080} height={1920} />
      <Composition id="C47-EmptyChairInterview" component={C47} durationInFrames={450} fps={FPS} width={1080} height={1920} />
    </>
  )
}
