import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { updateSession } from '@/utils/supabase/middleware'

export async function proxy(request: NextRequest) {
  // 1. First, check and update Supabase auth sessions
  const authResponse = await updateSession(request)

  // If updateSession decided to redirect (e.g. to /login), return that immediately
  if (authResponse.status === 307 || authResponse.status === 308) {
    return authResponse
  }

  // 2. Next, handle subdomain tenant rewrites and route aliases
  const hostname = request.headers.get('host') || ''
  const subdomain = hostname.split('.')[0]
  const path = request.nextUrl.pathname.toLowerCase()

  const isMainDomain = 
    hostname === 'localhost:3000' || 
    hostname === 'launchgrid.in' || 
    hostname === 'www.launchgrid.in' || 
    subdomain === 'www' || 
    subdomain === 'api'

  // Route alias handling for the main domain
  if (isMainDomain) {
    if (path === '/privacy') {
      return NextResponse.redirect(new URL('/legal/privacy', request.url))
    }
    if (path === '/terms') {
      return NextResponse.redirect(new URL('/legal/terms', request.url))
    }
    if (path === '/refund' || path === '/refund-policy') {
      return NextResponse.redirect(new URL('/legal/refund', request.url))
    }
    if (path === '/contact' || path === '/contact-us') {
      return NextResponse.redirect(new URL('/legal/contact', request.url))
    }
    
    return authResponse
  }

  // Merchant Subdomain routing
  // Aliases for legal routes on merchant storefront
  if (path === '/privacy') {
    const url = request.nextUrl.clone()
    url.pathname = `/store/${subdomain}/policies/privacy`
    return NextResponse.rewrite(url)
  }
  if (path === '/terms') {
    const url = request.nextUrl.clone()
    url.pathname = `/store/${subdomain}/policies/terms`
    return NextResponse.rewrite(url)
  }
  if (path === '/refund' || path === '/refund-policy') {
    const url = request.nextUrl.clone()
    url.pathname = `/store/${subdomain}/policies/refund`
    return NextResponse.rewrite(url)
  }
  if (path === '/shipping' || path === '/shipping-policy') {
    const url = request.nextUrl.clone()
    url.pathname = `/store/${subdomain}/policies/shipping`
    return NextResponse.rewrite(url)
  }
  if (path === '/contact' || path === '/contact-us') {
    const url = request.nextUrl.clone()
    url.pathname = `/store/${subdomain}`
    return NextResponse.rewrite(url)
  }

  // Rewrite to tenant-aware route
  const url = request.nextUrl.clone()
  url.pathname = `/store/${subdomain}${url.pathname}`
  
  const rewriteResponse = NextResponse.rewrite(url)
  
  // Important: Copy over the auth cookies generated by updateSession to the rewrite response
  authResponse.cookies.getAll().forEach(cookie => {
    rewriteResponse.cookies.set(cookie.name, cookie.value, cookie)
  })

  return rewriteResponse
}

export const config = {
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
}
